// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: comdex/oracle/v1beta1/params.proto

package comdex.oracle.v1beta1;

public final class ParamsOuterClass {
  private ParamsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface IBCParamsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:comdex.oracle.v1beta1.IBCParams)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string port = 1 [(.gogoproto.moretags) = "yaml:&#92;"port&#92;""];</code>
     * @return The port.
     */
    java.lang.String getPort();
    /**
     * <code>string port = 1 [(.gogoproto.moretags) = "yaml:&#92;"port&#92;""];</code>
     * @return The bytes for port.
     */
    com.google.protobuf.ByteString
        getPortBytes();

    /**
     * <code>string version = 2 [(.gogoproto.moretags) = "yaml:&#92;"version&#92;""];</code>
     * @return The version.
     */
    java.lang.String getVersion();
    /**
     * <code>string version = 2 [(.gogoproto.moretags) = "yaml:&#92;"version&#92;""];</code>
     * @return The bytes for version.
     */
    com.google.protobuf.ByteString
        getVersionBytes();
  }
  /**
   * Protobuf type {@code comdex.oracle.v1beta1.IBCParams}
   */
  public static final class IBCParams extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:comdex.oracle.v1beta1.IBCParams)
      IBCParamsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IBCParams.newBuilder() to construct.
    private IBCParams(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IBCParams() {
      port_ = "";
      version_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new IBCParams();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private IBCParams(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              port_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              version_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return comdex.oracle.v1beta1.ParamsOuterClass.internal_static_comdex_oracle_v1beta1_IBCParams_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return comdex.oracle.v1beta1.ParamsOuterClass.internal_static_comdex_oracle_v1beta1_IBCParams_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              comdex.oracle.v1beta1.ParamsOuterClass.IBCParams.class, comdex.oracle.v1beta1.ParamsOuterClass.IBCParams.Builder.class);
    }

    public static final int PORT_FIELD_NUMBER = 1;
    private volatile java.lang.Object port_;
    /**
     * <code>string port = 1 [(.gogoproto.moretags) = "yaml:&#92;"port&#92;""];</code>
     * @return The port.
     */
    @java.lang.Override
    public java.lang.String getPort() {
      java.lang.Object ref = port_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        port_ = s;
        return s;
      }
    }
    /**
     * <code>string port = 1 [(.gogoproto.moretags) = "yaml:&#92;"port&#92;""];</code>
     * @return The bytes for port.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPortBytes() {
      java.lang.Object ref = port_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        port_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERSION_FIELD_NUMBER = 2;
    private volatile java.lang.Object version_;
    /**
     * <code>string version = 2 [(.gogoproto.moretags) = "yaml:&#92;"version&#92;""];</code>
     * @return The version.
     */
    @java.lang.Override
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      }
    }
    /**
     * <code>string version = 2 [(.gogoproto.moretags) = "yaml:&#92;"version&#92;""];</code>
     * @return The bytes for version.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPortBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, port_);
      }
      if (!getVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, version_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPortBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, port_);
      }
      if (!getVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, version_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof comdex.oracle.v1beta1.ParamsOuterClass.IBCParams)) {
        return super.equals(obj);
      }
      comdex.oracle.v1beta1.ParamsOuterClass.IBCParams other = (comdex.oracle.v1beta1.ParamsOuterClass.IBCParams) obj;

      if (!getPort()
          .equals(other.getPort())) return false;
      if (!getVersion()
          .equals(other.getVersion())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static comdex.oracle.v1beta1.ParamsOuterClass.IBCParams parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static comdex.oracle.v1beta1.ParamsOuterClass.IBCParams parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static comdex.oracle.v1beta1.ParamsOuterClass.IBCParams parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static comdex.oracle.v1beta1.ParamsOuterClass.IBCParams parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static comdex.oracle.v1beta1.ParamsOuterClass.IBCParams parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static comdex.oracle.v1beta1.ParamsOuterClass.IBCParams parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static comdex.oracle.v1beta1.ParamsOuterClass.IBCParams parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static comdex.oracle.v1beta1.ParamsOuterClass.IBCParams parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static comdex.oracle.v1beta1.ParamsOuterClass.IBCParams parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static comdex.oracle.v1beta1.ParamsOuterClass.IBCParams parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static comdex.oracle.v1beta1.ParamsOuterClass.IBCParams parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static comdex.oracle.v1beta1.ParamsOuterClass.IBCParams parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(comdex.oracle.v1beta1.ParamsOuterClass.IBCParams prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code comdex.oracle.v1beta1.IBCParams}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:comdex.oracle.v1beta1.IBCParams)
        comdex.oracle.v1beta1.ParamsOuterClass.IBCParamsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return comdex.oracle.v1beta1.ParamsOuterClass.internal_static_comdex_oracle_v1beta1_IBCParams_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return comdex.oracle.v1beta1.ParamsOuterClass.internal_static_comdex_oracle_v1beta1_IBCParams_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                comdex.oracle.v1beta1.ParamsOuterClass.IBCParams.class, comdex.oracle.v1beta1.ParamsOuterClass.IBCParams.Builder.class);
      }

      // Construct using comdex.oracle.v1beta1.ParamsOuterClass.IBCParams.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        port_ = "";

        version_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return comdex.oracle.v1beta1.ParamsOuterClass.internal_static_comdex_oracle_v1beta1_IBCParams_descriptor;
      }

      @java.lang.Override
      public comdex.oracle.v1beta1.ParamsOuterClass.IBCParams getDefaultInstanceForType() {
        return comdex.oracle.v1beta1.ParamsOuterClass.IBCParams.getDefaultInstance();
      }

      @java.lang.Override
      public comdex.oracle.v1beta1.ParamsOuterClass.IBCParams build() {
        comdex.oracle.v1beta1.ParamsOuterClass.IBCParams result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public comdex.oracle.v1beta1.ParamsOuterClass.IBCParams buildPartial() {
        comdex.oracle.v1beta1.ParamsOuterClass.IBCParams result = new comdex.oracle.v1beta1.ParamsOuterClass.IBCParams(this);
        result.port_ = port_;
        result.version_ = version_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof comdex.oracle.v1beta1.ParamsOuterClass.IBCParams) {
          return mergeFrom((comdex.oracle.v1beta1.ParamsOuterClass.IBCParams)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(comdex.oracle.v1beta1.ParamsOuterClass.IBCParams other) {
        if (other == comdex.oracle.v1beta1.ParamsOuterClass.IBCParams.getDefaultInstance()) return this;
        if (!other.getPort().isEmpty()) {
          port_ = other.port_;
          onChanged();
        }
        if (!other.getVersion().isEmpty()) {
          version_ = other.version_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        comdex.oracle.v1beta1.ParamsOuterClass.IBCParams parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (comdex.oracle.v1beta1.ParamsOuterClass.IBCParams) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object port_ = "";
      /**
       * <code>string port = 1 [(.gogoproto.moretags) = "yaml:&#92;"port&#92;""];</code>
       * @return The port.
       */
      public java.lang.String getPort() {
        java.lang.Object ref = port_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          port_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string port = 1 [(.gogoproto.moretags) = "yaml:&#92;"port&#92;""];</code>
       * @return The bytes for port.
       */
      public com.google.protobuf.ByteString
          getPortBytes() {
        java.lang.Object ref = port_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          port_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string port = 1 [(.gogoproto.moretags) = "yaml:&#92;"port&#92;""];</code>
       * @param value The port to set.
       * @return This builder for chaining.
       */
      public Builder setPort(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string port = 1 [(.gogoproto.moretags) = "yaml:&#92;"port&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearPort() {
        
        port_ = getDefaultInstance().getPort();
        onChanged();
        return this;
      }
      /**
       * <code>string port = 1 [(.gogoproto.moretags) = "yaml:&#92;"port&#92;""];</code>
       * @param value The bytes for port to set.
       * @return This builder for chaining.
       */
      public Builder setPortBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        port_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object version_ = "";
      /**
       * <code>string version = 2 [(.gogoproto.moretags) = "yaml:&#92;"version&#92;""];</code>
       * @return The version.
       */
      public java.lang.String getVersion() {
        java.lang.Object ref = version_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string version = 2 [(.gogoproto.moretags) = "yaml:&#92;"version&#92;""];</code>
       * @return The bytes for version.
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        java.lang.Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string version = 2 [(.gogoproto.moretags) = "yaml:&#92;"version&#92;""];</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string version = 2 [(.gogoproto.moretags) = "yaml:&#92;"version&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string version = 2 [(.gogoproto.moretags) = "yaml:&#92;"version&#92;""];</code>
       * @param value The bytes for version to set.
       * @return This builder for chaining.
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        version_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:comdex.oracle.v1beta1.IBCParams)
    }

    // @@protoc_insertion_point(class_scope:comdex.oracle.v1beta1.IBCParams)
    private static final comdex.oracle.v1beta1.ParamsOuterClass.IBCParams DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new comdex.oracle.v1beta1.ParamsOuterClass.IBCParams();
    }

    public static comdex.oracle.v1beta1.ParamsOuterClass.IBCParams getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IBCParams>
        PARSER = new com.google.protobuf.AbstractParser<IBCParams>() {
      @java.lang.Override
      public IBCParams parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IBCParams(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<IBCParams> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IBCParams> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public comdex.oracle.v1beta1.ParamsOuterClass.IBCParams getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OracleParamsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:comdex.oracle.v1beta1.OracleParams)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 ask_count = 1 [(.gogoproto.moretags) = "yaml:&#92;"ask_count&#92;""];</code>
     * @return The askCount.
     */
    long getAskCount();

    /**
     * <code>uint64 min_count = 2 [(.gogoproto.moretags) = "yaml:&#92;"min_count&#92;""];</code>
     * @return The minCount.
     */
    long getMinCount();

    /**
     * <code>uint64 multiplier = 3 [(.gogoproto.moretags) = "yaml:&#92;"multiplier&#92;""];</code>
     * @return The multiplier.
     */
    long getMultiplier();
  }
  /**
   * Protobuf type {@code comdex.oracle.v1beta1.OracleParams}
   */
  public static final class OracleParams extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:comdex.oracle.v1beta1.OracleParams)
      OracleParamsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OracleParams.newBuilder() to construct.
    private OracleParams(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OracleParams() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new OracleParams();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OracleParams(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              askCount_ = input.readUInt64();
              break;
            }
            case 16: {

              minCount_ = input.readUInt64();
              break;
            }
            case 24: {

              multiplier_ = input.readUInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return comdex.oracle.v1beta1.ParamsOuterClass.internal_static_comdex_oracle_v1beta1_OracleParams_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return comdex.oracle.v1beta1.ParamsOuterClass.internal_static_comdex_oracle_v1beta1_OracleParams_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              comdex.oracle.v1beta1.ParamsOuterClass.OracleParams.class, comdex.oracle.v1beta1.ParamsOuterClass.OracleParams.Builder.class);
    }

    public static final int ASK_COUNT_FIELD_NUMBER = 1;
    private long askCount_;
    /**
     * <code>uint64 ask_count = 1 [(.gogoproto.moretags) = "yaml:&#92;"ask_count&#92;""];</code>
     * @return The askCount.
     */
    @java.lang.Override
    public long getAskCount() {
      return askCount_;
    }

    public static final int MIN_COUNT_FIELD_NUMBER = 2;
    private long minCount_;
    /**
     * <code>uint64 min_count = 2 [(.gogoproto.moretags) = "yaml:&#92;"min_count&#92;""];</code>
     * @return The minCount.
     */
    @java.lang.Override
    public long getMinCount() {
      return minCount_;
    }

    public static final int MULTIPLIER_FIELD_NUMBER = 3;
    private long multiplier_;
    /**
     * <code>uint64 multiplier = 3 [(.gogoproto.moretags) = "yaml:&#92;"multiplier&#92;""];</code>
     * @return The multiplier.
     */
    @java.lang.Override
    public long getMultiplier() {
      return multiplier_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (askCount_ != 0L) {
        output.writeUInt64(1, askCount_);
      }
      if (minCount_ != 0L) {
        output.writeUInt64(2, minCount_);
      }
      if (multiplier_ != 0L) {
        output.writeUInt64(3, multiplier_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (askCount_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, askCount_);
      }
      if (minCount_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, minCount_);
      }
      if (multiplier_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, multiplier_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof comdex.oracle.v1beta1.ParamsOuterClass.OracleParams)) {
        return super.equals(obj);
      }
      comdex.oracle.v1beta1.ParamsOuterClass.OracleParams other = (comdex.oracle.v1beta1.ParamsOuterClass.OracleParams) obj;

      if (getAskCount()
          != other.getAskCount()) return false;
      if (getMinCount()
          != other.getMinCount()) return false;
      if (getMultiplier()
          != other.getMultiplier()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ASK_COUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getAskCount());
      hash = (37 * hash) + MIN_COUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMinCount());
      hash = (37 * hash) + MULTIPLIER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMultiplier());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static comdex.oracle.v1beta1.ParamsOuterClass.OracleParams parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static comdex.oracle.v1beta1.ParamsOuterClass.OracleParams parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static comdex.oracle.v1beta1.ParamsOuterClass.OracleParams parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static comdex.oracle.v1beta1.ParamsOuterClass.OracleParams parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static comdex.oracle.v1beta1.ParamsOuterClass.OracleParams parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static comdex.oracle.v1beta1.ParamsOuterClass.OracleParams parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static comdex.oracle.v1beta1.ParamsOuterClass.OracleParams parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static comdex.oracle.v1beta1.ParamsOuterClass.OracleParams parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static comdex.oracle.v1beta1.ParamsOuterClass.OracleParams parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static comdex.oracle.v1beta1.ParamsOuterClass.OracleParams parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static comdex.oracle.v1beta1.ParamsOuterClass.OracleParams parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static comdex.oracle.v1beta1.ParamsOuterClass.OracleParams parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(comdex.oracle.v1beta1.ParamsOuterClass.OracleParams prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code comdex.oracle.v1beta1.OracleParams}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:comdex.oracle.v1beta1.OracleParams)
        comdex.oracle.v1beta1.ParamsOuterClass.OracleParamsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return comdex.oracle.v1beta1.ParamsOuterClass.internal_static_comdex_oracle_v1beta1_OracleParams_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return comdex.oracle.v1beta1.ParamsOuterClass.internal_static_comdex_oracle_v1beta1_OracleParams_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                comdex.oracle.v1beta1.ParamsOuterClass.OracleParams.class, comdex.oracle.v1beta1.ParamsOuterClass.OracleParams.Builder.class);
      }

      // Construct using comdex.oracle.v1beta1.ParamsOuterClass.OracleParams.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        askCount_ = 0L;

        minCount_ = 0L;

        multiplier_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return comdex.oracle.v1beta1.ParamsOuterClass.internal_static_comdex_oracle_v1beta1_OracleParams_descriptor;
      }

      @java.lang.Override
      public comdex.oracle.v1beta1.ParamsOuterClass.OracleParams getDefaultInstanceForType() {
        return comdex.oracle.v1beta1.ParamsOuterClass.OracleParams.getDefaultInstance();
      }

      @java.lang.Override
      public comdex.oracle.v1beta1.ParamsOuterClass.OracleParams build() {
        comdex.oracle.v1beta1.ParamsOuterClass.OracleParams result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public comdex.oracle.v1beta1.ParamsOuterClass.OracleParams buildPartial() {
        comdex.oracle.v1beta1.ParamsOuterClass.OracleParams result = new comdex.oracle.v1beta1.ParamsOuterClass.OracleParams(this);
        result.askCount_ = askCount_;
        result.minCount_ = minCount_;
        result.multiplier_ = multiplier_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof comdex.oracle.v1beta1.ParamsOuterClass.OracleParams) {
          return mergeFrom((comdex.oracle.v1beta1.ParamsOuterClass.OracleParams)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(comdex.oracle.v1beta1.ParamsOuterClass.OracleParams other) {
        if (other == comdex.oracle.v1beta1.ParamsOuterClass.OracleParams.getDefaultInstance()) return this;
        if (other.getAskCount() != 0L) {
          setAskCount(other.getAskCount());
        }
        if (other.getMinCount() != 0L) {
          setMinCount(other.getMinCount());
        }
        if (other.getMultiplier() != 0L) {
          setMultiplier(other.getMultiplier());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        comdex.oracle.v1beta1.ParamsOuterClass.OracleParams parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (comdex.oracle.v1beta1.ParamsOuterClass.OracleParams) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long askCount_ ;
      /**
       * <code>uint64 ask_count = 1 [(.gogoproto.moretags) = "yaml:&#92;"ask_count&#92;""];</code>
       * @return The askCount.
       */
      @java.lang.Override
      public long getAskCount() {
        return askCount_;
      }
      /**
       * <code>uint64 ask_count = 1 [(.gogoproto.moretags) = "yaml:&#92;"ask_count&#92;""];</code>
       * @param value The askCount to set.
       * @return This builder for chaining.
       */
      public Builder setAskCount(long value) {
        
        askCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 ask_count = 1 [(.gogoproto.moretags) = "yaml:&#92;"ask_count&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearAskCount() {
        
        askCount_ = 0L;
        onChanged();
        return this;
      }

      private long minCount_ ;
      /**
       * <code>uint64 min_count = 2 [(.gogoproto.moretags) = "yaml:&#92;"min_count&#92;""];</code>
       * @return The minCount.
       */
      @java.lang.Override
      public long getMinCount() {
        return minCount_;
      }
      /**
       * <code>uint64 min_count = 2 [(.gogoproto.moretags) = "yaml:&#92;"min_count&#92;""];</code>
       * @param value The minCount to set.
       * @return This builder for chaining.
       */
      public Builder setMinCount(long value) {
        
        minCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 min_count = 2 [(.gogoproto.moretags) = "yaml:&#92;"min_count&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearMinCount() {
        
        minCount_ = 0L;
        onChanged();
        return this;
      }

      private long multiplier_ ;
      /**
       * <code>uint64 multiplier = 3 [(.gogoproto.moretags) = "yaml:&#92;"multiplier&#92;""];</code>
       * @return The multiplier.
       */
      @java.lang.Override
      public long getMultiplier() {
        return multiplier_;
      }
      /**
       * <code>uint64 multiplier = 3 [(.gogoproto.moretags) = "yaml:&#92;"multiplier&#92;""];</code>
       * @param value The multiplier to set.
       * @return This builder for chaining.
       */
      public Builder setMultiplier(long value) {
        
        multiplier_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 multiplier = 3 [(.gogoproto.moretags) = "yaml:&#92;"multiplier&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearMultiplier() {
        
        multiplier_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:comdex.oracle.v1beta1.OracleParams)
    }

    // @@protoc_insertion_point(class_scope:comdex.oracle.v1beta1.OracleParams)
    private static final comdex.oracle.v1beta1.ParamsOuterClass.OracleParams DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new comdex.oracle.v1beta1.ParamsOuterClass.OracleParams();
    }

    public static comdex.oracle.v1beta1.ParamsOuterClass.OracleParams getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OracleParams>
        PARSER = new com.google.protobuf.AbstractParser<OracleParams>() {
      @java.lang.Override
      public OracleParams parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OracleParams(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OracleParams> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OracleParams> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public comdex.oracle.v1beta1.ParamsOuterClass.OracleParams getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ParamsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:comdex.oracle.v1beta1.Params)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.comdex.oracle.v1beta1.IBCParams ibc = 1 [(.gogoproto.nullable) = false, (.gogoproto.customname) = "IBC", (.gogoproto.moretags) = "yaml:&#92;"ibc&#92;""];</code>
     * @return Whether the ibc field is set.
     */
    boolean hasIbc();
    /**
     * <code>.comdex.oracle.v1beta1.IBCParams ibc = 1 [(.gogoproto.nullable) = false, (.gogoproto.customname) = "IBC", (.gogoproto.moretags) = "yaml:&#92;"ibc&#92;""];</code>
     * @return The ibc.
     */
    comdex.oracle.v1beta1.ParamsOuterClass.IBCParams getIbc();
    /**
     * <code>.comdex.oracle.v1beta1.IBCParams ibc = 1 [(.gogoproto.nullable) = false, (.gogoproto.customname) = "IBC", (.gogoproto.moretags) = "yaml:&#92;"ibc&#92;""];</code>
     */
    comdex.oracle.v1beta1.ParamsOuterClass.IBCParamsOrBuilder getIbcOrBuilder();

    /**
     * <code>.comdex.oracle.v1beta1.OracleParams oracle = 2 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"oracle&#92;""];</code>
     * @return Whether the oracle field is set.
     */
    boolean hasOracle();
    /**
     * <code>.comdex.oracle.v1beta1.OracleParams oracle = 2 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"oracle&#92;""];</code>
     * @return The oracle.
     */
    comdex.oracle.v1beta1.ParamsOuterClass.OracleParams getOracle();
    /**
     * <code>.comdex.oracle.v1beta1.OracleParams oracle = 2 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"oracle&#92;""];</code>
     */
    comdex.oracle.v1beta1.ParamsOuterClass.OracleParamsOrBuilder getOracleOrBuilder();
  }
  /**
   * Protobuf type {@code comdex.oracle.v1beta1.Params}
   */
  public static final class Params extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:comdex.oracle.v1beta1.Params)
      ParamsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Params.newBuilder() to construct.
    private Params(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Params() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Params();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Params(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              comdex.oracle.v1beta1.ParamsOuterClass.IBCParams.Builder subBuilder = null;
              if (ibc_ != null) {
                subBuilder = ibc_.toBuilder();
              }
              ibc_ = input.readMessage(comdex.oracle.v1beta1.ParamsOuterClass.IBCParams.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(ibc_);
                ibc_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              comdex.oracle.v1beta1.ParamsOuterClass.OracleParams.Builder subBuilder = null;
              if (oracle_ != null) {
                subBuilder = oracle_.toBuilder();
              }
              oracle_ = input.readMessage(comdex.oracle.v1beta1.ParamsOuterClass.OracleParams.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(oracle_);
                oracle_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return comdex.oracle.v1beta1.ParamsOuterClass.internal_static_comdex_oracle_v1beta1_Params_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return comdex.oracle.v1beta1.ParamsOuterClass.internal_static_comdex_oracle_v1beta1_Params_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              comdex.oracle.v1beta1.ParamsOuterClass.Params.class, comdex.oracle.v1beta1.ParamsOuterClass.Params.Builder.class);
    }

    public static final int IBC_FIELD_NUMBER = 1;
    private comdex.oracle.v1beta1.ParamsOuterClass.IBCParams ibc_;
    /**
     * <code>.comdex.oracle.v1beta1.IBCParams ibc = 1 [(.gogoproto.nullable) = false, (.gogoproto.customname) = "IBC", (.gogoproto.moretags) = "yaml:&#92;"ibc&#92;""];</code>
     * @return Whether the ibc field is set.
     */
    @java.lang.Override
    public boolean hasIbc() {
      return ibc_ != null;
    }
    /**
     * <code>.comdex.oracle.v1beta1.IBCParams ibc = 1 [(.gogoproto.nullable) = false, (.gogoproto.customname) = "IBC", (.gogoproto.moretags) = "yaml:&#92;"ibc&#92;""];</code>
     * @return The ibc.
     */
    @java.lang.Override
    public comdex.oracle.v1beta1.ParamsOuterClass.IBCParams getIbc() {
      return ibc_ == null ? comdex.oracle.v1beta1.ParamsOuterClass.IBCParams.getDefaultInstance() : ibc_;
    }
    /**
     * <code>.comdex.oracle.v1beta1.IBCParams ibc = 1 [(.gogoproto.nullable) = false, (.gogoproto.customname) = "IBC", (.gogoproto.moretags) = "yaml:&#92;"ibc&#92;""];</code>
     */
    @java.lang.Override
    public comdex.oracle.v1beta1.ParamsOuterClass.IBCParamsOrBuilder getIbcOrBuilder() {
      return getIbc();
    }

    public static final int ORACLE_FIELD_NUMBER = 2;
    private comdex.oracle.v1beta1.ParamsOuterClass.OracleParams oracle_;
    /**
     * <code>.comdex.oracle.v1beta1.OracleParams oracle = 2 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"oracle&#92;""];</code>
     * @return Whether the oracle field is set.
     */
    @java.lang.Override
    public boolean hasOracle() {
      return oracle_ != null;
    }
    /**
     * <code>.comdex.oracle.v1beta1.OracleParams oracle = 2 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"oracle&#92;""];</code>
     * @return The oracle.
     */
    @java.lang.Override
    public comdex.oracle.v1beta1.ParamsOuterClass.OracleParams getOracle() {
      return oracle_ == null ? comdex.oracle.v1beta1.ParamsOuterClass.OracleParams.getDefaultInstance() : oracle_;
    }
    /**
     * <code>.comdex.oracle.v1beta1.OracleParams oracle = 2 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"oracle&#92;""];</code>
     */
    @java.lang.Override
    public comdex.oracle.v1beta1.ParamsOuterClass.OracleParamsOrBuilder getOracleOrBuilder() {
      return getOracle();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (ibc_ != null) {
        output.writeMessage(1, getIbc());
      }
      if (oracle_ != null) {
        output.writeMessage(2, getOracle());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (ibc_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getIbc());
      }
      if (oracle_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getOracle());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof comdex.oracle.v1beta1.ParamsOuterClass.Params)) {
        return super.equals(obj);
      }
      comdex.oracle.v1beta1.ParamsOuterClass.Params other = (comdex.oracle.v1beta1.ParamsOuterClass.Params) obj;

      if (hasIbc() != other.hasIbc()) return false;
      if (hasIbc()) {
        if (!getIbc()
            .equals(other.getIbc())) return false;
      }
      if (hasOracle() != other.hasOracle()) return false;
      if (hasOracle()) {
        if (!getOracle()
            .equals(other.getOracle())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasIbc()) {
        hash = (37 * hash) + IBC_FIELD_NUMBER;
        hash = (53 * hash) + getIbc().hashCode();
      }
      if (hasOracle()) {
        hash = (37 * hash) + ORACLE_FIELD_NUMBER;
        hash = (53 * hash) + getOracle().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static comdex.oracle.v1beta1.ParamsOuterClass.Params parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static comdex.oracle.v1beta1.ParamsOuterClass.Params parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static comdex.oracle.v1beta1.ParamsOuterClass.Params parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static comdex.oracle.v1beta1.ParamsOuterClass.Params parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static comdex.oracle.v1beta1.ParamsOuterClass.Params parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static comdex.oracle.v1beta1.ParamsOuterClass.Params parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static comdex.oracle.v1beta1.ParamsOuterClass.Params parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static comdex.oracle.v1beta1.ParamsOuterClass.Params parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static comdex.oracle.v1beta1.ParamsOuterClass.Params parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static comdex.oracle.v1beta1.ParamsOuterClass.Params parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static comdex.oracle.v1beta1.ParamsOuterClass.Params parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static comdex.oracle.v1beta1.ParamsOuterClass.Params parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(comdex.oracle.v1beta1.ParamsOuterClass.Params prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code comdex.oracle.v1beta1.Params}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:comdex.oracle.v1beta1.Params)
        comdex.oracle.v1beta1.ParamsOuterClass.ParamsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return comdex.oracle.v1beta1.ParamsOuterClass.internal_static_comdex_oracle_v1beta1_Params_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return comdex.oracle.v1beta1.ParamsOuterClass.internal_static_comdex_oracle_v1beta1_Params_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                comdex.oracle.v1beta1.ParamsOuterClass.Params.class, comdex.oracle.v1beta1.ParamsOuterClass.Params.Builder.class);
      }

      // Construct using comdex.oracle.v1beta1.ParamsOuterClass.Params.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (ibcBuilder_ == null) {
          ibc_ = null;
        } else {
          ibc_ = null;
          ibcBuilder_ = null;
        }
        if (oracleBuilder_ == null) {
          oracle_ = null;
        } else {
          oracle_ = null;
          oracleBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return comdex.oracle.v1beta1.ParamsOuterClass.internal_static_comdex_oracle_v1beta1_Params_descriptor;
      }

      @java.lang.Override
      public comdex.oracle.v1beta1.ParamsOuterClass.Params getDefaultInstanceForType() {
        return comdex.oracle.v1beta1.ParamsOuterClass.Params.getDefaultInstance();
      }

      @java.lang.Override
      public comdex.oracle.v1beta1.ParamsOuterClass.Params build() {
        comdex.oracle.v1beta1.ParamsOuterClass.Params result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public comdex.oracle.v1beta1.ParamsOuterClass.Params buildPartial() {
        comdex.oracle.v1beta1.ParamsOuterClass.Params result = new comdex.oracle.v1beta1.ParamsOuterClass.Params(this);
        if (ibcBuilder_ == null) {
          result.ibc_ = ibc_;
        } else {
          result.ibc_ = ibcBuilder_.build();
        }
        if (oracleBuilder_ == null) {
          result.oracle_ = oracle_;
        } else {
          result.oracle_ = oracleBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof comdex.oracle.v1beta1.ParamsOuterClass.Params) {
          return mergeFrom((comdex.oracle.v1beta1.ParamsOuterClass.Params)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(comdex.oracle.v1beta1.ParamsOuterClass.Params other) {
        if (other == comdex.oracle.v1beta1.ParamsOuterClass.Params.getDefaultInstance()) return this;
        if (other.hasIbc()) {
          mergeIbc(other.getIbc());
        }
        if (other.hasOracle()) {
          mergeOracle(other.getOracle());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        comdex.oracle.v1beta1.ParamsOuterClass.Params parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (comdex.oracle.v1beta1.ParamsOuterClass.Params) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private comdex.oracle.v1beta1.ParamsOuterClass.IBCParams ibc_;
      private com.google.protobuf.SingleFieldBuilderV3<
          comdex.oracle.v1beta1.ParamsOuterClass.IBCParams, comdex.oracle.v1beta1.ParamsOuterClass.IBCParams.Builder, comdex.oracle.v1beta1.ParamsOuterClass.IBCParamsOrBuilder> ibcBuilder_;
      /**
       * <code>.comdex.oracle.v1beta1.IBCParams ibc = 1 [(.gogoproto.nullable) = false, (.gogoproto.customname) = "IBC", (.gogoproto.moretags) = "yaml:&#92;"ibc&#92;""];</code>
       * @return Whether the ibc field is set.
       */
      public boolean hasIbc() {
        return ibcBuilder_ != null || ibc_ != null;
      }
      /**
       * <code>.comdex.oracle.v1beta1.IBCParams ibc = 1 [(.gogoproto.nullable) = false, (.gogoproto.customname) = "IBC", (.gogoproto.moretags) = "yaml:&#92;"ibc&#92;""];</code>
       * @return The ibc.
       */
      public comdex.oracle.v1beta1.ParamsOuterClass.IBCParams getIbc() {
        if (ibcBuilder_ == null) {
          return ibc_ == null ? comdex.oracle.v1beta1.ParamsOuterClass.IBCParams.getDefaultInstance() : ibc_;
        } else {
          return ibcBuilder_.getMessage();
        }
      }
      /**
       * <code>.comdex.oracle.v1beta1.IBCParams ibc = 1 [(.gogoproto.nullable) = false, (.gogoproto.customname) = "IBC", (.gogoproto.moretags) = "yaml:&#92;"ibc&#92;""];</code>
       */
      public Builder setIbc(comdex.oracle.v1beta1.ParamsOuterClass.IBCParams value) {
        if (ibcBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ibc_ = value;
          onChanged();
        } else {
          ibcBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.comdex.oracle.v1beta1.IBCParams ibc = 1 [(.gogoproto.nullable) = false, (.gogoproto.customname) = "IBC", (.gogoproto.moretags) = "yaml:&#92;"ibc&#92;""];</code>
       */
      public Builder setIbc(
          comdex.oracle.v1beta1.ParamsOuterClass.IBCParams.Builder builderForValue) {
        if (ibcBuilder_ == null) {
          ibc_ = builderForValue.build();
          onChanged();
        } else {
          ibcBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.comdex.oracle.v1beta1.IBCParams ibc = 1 [(.gogoproto.nullable) = false, (.gogoproto.customname) = "IBC", (.gogoproto.moretags) = "yaml:&#92;"ibc&#92;""];</code>
       */
      public Builder mergeIbc(comdex.oracle.v1beta1.ParamsOuterClass.IBCParams value) {
        if (ibcBuilder_ == null) {
          if (ibc_ != null) {
            ibc_ =
              comdex.oracle.v1beta1.ParamsOuterClass.IBCParams.newBuilder(ibc_).mergeFrom(value).buildPartial();
          } else {
            ibc_ = value;
          }
          onChanged();
        } else {
          ibcBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.comdex.oracle.v1beta1.IBCParams ibc = 1 [(.gogoproto.nullable) = false, (.gogoproto.customname) = "IBC", (.gogoproto.moretags) = "yaml:&#92;"ibc&#92;""];</code>
       */
      public Builder clearIbc() {
        if (ibcBuilder_ == null) {
          ibc_ = null;
          onChanged();
        } else {
          ibc_ = null;
          ibcBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.comdex.oracle.v1beta1.IBCParams ibc = 1 [(.gogoproto.nullable) = false, (.gogoproto.customname) = "IBC", (.gogoproto.moretags) = "yaml:&#92;"ibc&#92;""];</code>
       */
      public comdex.oracle.v1beta1.ParamsOuterClass.IBCParams.Builder getIbcBuilder() {
        
        onChanged();
        return getIbcFieldBuilder().getBuilder();
      }
      /**
       * <code>.comdex.oracle.v1beta1.IBCParams ibc = 1 [(.gogoproto.nullable) = false, (.gogoproto.customname) = "IBC", (.gogoproto.moretags) = "yaml:&#92;"ibc&#92;""];</code>
       */
      public comdex.oracle.v1beta1.ParamsOuterClass.IBCParamsOrBuilder getIbcOrBuilder() {
        if (ibcBuilder_ != null) {
          return ibcBuilder_.getMessageOrBuilder();
        } else {
          return ibc_ == null ?
              comdex.oracle.v1beta1.ParamsOuterClass.IBCParams.getDefaultInstance() : ibc_;
        }
      }
      /**
       * <code>.comdex.oracle.v1beta1.IBCParams ibc = 1 [(.gogoproto.nullable) = false, (.gogoproto.customname) = "IBC", (.gogoproto.moretags) = "yaml:&#92;"ibc&#92;""];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          comdex.oracle.v1beta1.ParamsOuterClass.IBCParams, comdex.oracle.v1beta1.ParamsOuterClass.IBCParams.Builder, comdex.oracle.v1beta1.ParamsOuterClass.IBCParamsOrBuilder> 
          getIbcFieldBuilder() {
        if (ibcBuilder_ == null) {
          ibcBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              comdex.oracle.v1beta1.ParamsOuterClass.IBCParams, comdex.oracle.v1beta1.ParamsOuterClass.IBCParams.Builder, comdex.oracle.v1beta1.ParamsOuterClass.IBCParamsOrBuilder>(
                  getIbc(),
                  getParentForChildren(),
                  isClean());
          ibc_ = null;
        }
        return ibcBuilder_;
      }

      private comdex.oracle.v1beta1.ParamsOuterClass.OracleParams oracle_;
      private com.google.protobuf.SingleFieldBuilderV3<
          comdex.oracle.v1beta1.ParamsOuterClass.OracleParams, comdex.oracle.v1beta1.ParamsOuterClass.OracleParams.Builder, comdex.oracle.v1beta1.ParamsOuterClass.OracleParamsOrBuilder> oracleBuilder_;
      /**
       * <code>.comdex.oracle.v1beta1.OracleParams oracle = 2 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"oracle&#92;""];</code>
       * @return Whether the oracle field is set.
       */
      public boolean hasOracle() {
        return oracleBuilder_ != null || oracle_ != null;
      }
      /**
       * <code>.comdex.oracle.v1beta1.OracleParams oracle = 2 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"oracle&#92;""];</code>
       * @return The oracle.
       */
      public comdex.oracle.v1beta1.ParamsOuterClass.OracleParams getOracle() {
        if (oracleBuilder_ == null) {
          return oracle_ == null ? comdex.oracle.v1beta1.ParamsOuterClass.OracleParams.getDefaultInstance() : oracle_;
        } else {
          return oracleBuilder_.getMessage();
        }
      }
      /**
       * <code>.comdex.oracle.v1beta1.OracleParams oracle = 2 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"oracle&#92;""];</code>
       */
      public Builder setOracle(comdex.oracle.v1beta1.ParamsOuterClass.OracleParams value) {
        if (oracleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          oracle_ = value;
          onChanged();
        } else {
          oracleBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.comdex.oracle.v1beta1.OracleParams oracle = 2 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"oracle&#92;""];</code>
       */
      public Builder setOracle(
          comdex.oracle.v1beta1.ParamsOuterClass.OracleParams.Builder builderForValue) {
        if (oracleBuilder_ == null) {
          oracle_ = builderForValue.build();
          onChanged();
        } else {
          oracleBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.comdex.oracle.v1beta1.OracleParams oracle = 2 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"oracle&#92;""];</code>
       */
      public Builder mergeOracle(comdex.oracle.v1beta1.ParamsOuterClass.OracleParams value) {
        if (oracleBuilder_ == null) {
          if (oracle_ != null) {
            oracle_ =
              comdex.oracle.v1beta1.ParamsOuterClass.OracleParams.newBuilder(oracle_).mergeFrom(value).buildPartial();
          } else {
            oracle_ = value;
          }
          onChanged();
        } else {
          oracleBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.comdex.oracle.v1beta1.OracleParams oracle = 2 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"oracle&#92;""];</code>
       */
      public Builder clearOracle() {
        if (oracleBuilder_ == null) {
          oracle_ = null;
          onChanged();
        } else {
          oracle_ = null;
          oracleBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.comdex.oracle.v1beta1.OracleParams oracle = 2 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"oracle&#92;""];</code>
       */
      public comdex.oracle.v1beta1.ParamsOuterClass.OracleParams.Builder getOracleBuilder() {
        
        onChanged();
        return getOracleFieldBuilder().getBuilder();
      }
      /**
       * <code>.comdex.oracle.v1beta1.OracleParams oracle = 2 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"oracle&#92;""];</code>
       */
      public comdex.oracle.v1beta1.ParamsOuterClass.OracleParamsOrBuilder getOracleOrBuilder() {
        if (oracleBuilder_ != null) {
          return oracleBuilder_.getMessageOrBuilder();
        } else {
          return oracle_ == null ?
              comdex.oracle.v1beta1.ParamsOuterClass.OracleParams.getDefaultInstance() : oracle_;
        }
      }
      /**
       * <code>.comdex.oracle.v1beta1.OracleParams oracle = 2 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"oracle&#92;""];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          comdex.oracle.v1beta1.ParamsOuterClass.OracleParams, comdex.oracle.v1beta1.ParamsOuterClass.OracleParams.Builder, comdex.oracle.v1beta1.ParamsOuterClass.OracleParamsOrBuilder> 
          getOracleFieldBuilder() {
        if (oracleBuilder_ == null) {
          oracleBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              comdex.oracle.v1beta1.ParamsOuterClass.OracleParams, comdex.oracle.v1beta1.ParamsOuterClass.OracleParams.Builder, comdex.oracle.v1beta1.ParamsOuterClass.OracleParamsOrBuilder>(
                  getOracle(),
                  getParentForChildren(),
                  isClean());
          oracle_ = null;
        }
        return oracleBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:comdex.oracle.v1beta1.Params)
    }

    // @@protoc_insertion_point(class_scope:comdex.oracle.v1beta1.Params)
    private static final comdex.oracle.v1beta1.ParamsOuterClass.Params DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new comdex.oracle.v1beta1.ParamsOuterClass.Params();
    }

    public static comdex.oracle.v1beta1.ParamsOuterClass.Params getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Params>
        PARSER = new com.google.protobuf.AbstractParser<Params>() {
      @java.lang.Override
      public Params parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Params(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Params> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Params> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public comdex.oracle.v1beta1.ParamsOuterClass.Params getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_comdex_oracle_v1beta1_IBCParams_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_comdex_oracle_v1beta1_IBCParams_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_comdex_oracle_v1beta1_OracleParams_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_comdex_oracle_v1beta1_OracleParams_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_comdex_oracle_v1beta1_Params_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_comdex_oracle_v1beta1_Params_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"comdex/oracle/v1beta1/params.proto\022\025co" +
      "mdex.oracle.v1beta1\032\024gogoproto/gogo.prot" +
      "o\"O\n\tIBCParams\022\035\n\004port\030\001 \001(\tB\017\362\336\037\013yaml:\"" +
      "port\"\022#\n\007version\030\002 \001(\tB\022\362\336\037\016yaml:\"versio" +
      "n\"\"\213\001\n\014OracleParams\022\'\n\task_count\030\001 \001(\004B\024" +
      "\362\336\037\020yaml:\"ask_count\"\022\'\n\tmin_count\030\002 \001(\004B" +
      "\024\362\336\037\020yaml:\"min_count\"\022)\n\nmultiplier\030\003 \001(" +
      "\004B\025\362\336\037\021yaml:\"multiplier\"\"\236\001\n\006Params\022H\n\003i" +
      "bc\030\001 \001(\0132 .comdex.oracle.v1beta1.IBCPara" +
      "msB\031\342\336\037\003IBC\362\336\037\nyaml:\"ibc\"\310\336\037\000\022J\n\006oracle\030" +
      "\002 \001(\0132#.comdex.oracle.v1beta1.OraclePara" +
      "msB\025\362\336\037\ryaml:\"oracle\"\310\336\037\000B:Z0github.com/" +
      "comdex-official/comdex/x/oracle/types\250\342\036" +
      "\000\310\341\036\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.GoGoProtos.getDescriptor(),
        });
    internal_static_comdex_oracle_v1beta1_IBCParams_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_comdex_oracle_v1beta1_IBCParams_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_comdex_oracle_v1beta1_IBCParams_descriptor,
        new java.lang.String[] { "Port", "Version", });
    internal_static_comdex_oracle_v1beta1_OracleParams_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_comdex_oracle_v1beta1_OracleParams_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_comdex_oracle_v1beta1_OracleParams_descriptor,
        new java.lang.String[] { "AskCount", "MinCount", "Multiplier", });
    internal_static_comdex_oracle_v1beta1_Params_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_comdex_oracle_v1beta1_Params_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_comdex_oracle_v1beta1_Params_descriptor,
        new java.lang.String[] { "Ibc", "Oracle", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf.GoGoProtos.customname);
    registry.add(com.google.protobuf.GoGoProtos.equalAll);
    registry.add(com.google.protobuf.GoGoProtos.goprotoGettersAll);
    registry.add(com.google.protobuf.GoGoProtos.moretags);
    registry.add(com.google.protobuf.GoGoProtos.nullable);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.GoGoProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
