// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: panacea/did/v2/tx.proto

package panacea.did.v2;

public final class Tx {
  private Tx() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_panacea_did_v2_MsgCreateDID_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_panacea_did_v2_MsgCreateDID_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_panacea_did_v2_MsgCreateDIDResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_panacea_did_v2_MsgCreateDIDResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_panacea_did_v2_MsgUpdateDID_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_panacea_did_v2_MsgUpdateDID_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_panacea_did_v2_MsgUpdateDIDResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_panacea_did_v2_MsgUpdateDIDResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_panacea_did_v2_MsgDeactivateDID_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_panacea_did_v2_MsgDeactivateDID_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_panacea_did_v2_MsgDeactivateDIDResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_panacea_did_v2_MsgDeactivateDIDResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027panacea/did/v2/tx.proto\022\016panacea.did.v" +
      "2\032\024gogoproto/gogo.proto\032\030panacea/did/v2/" +
      "did.proto\"\223\001\n\014MsgCreateDID\022\013\n\003did\030\001 \001(\t\022" +
      "-\n\010document\030\002 \001(\0132\033.panacea.did.v2.DIDDo" +
      "cument\022\036\n\026verification_method_id\030\003 \001(\t\022\021" +
      "\n\tsignature\030\004 \001(\014\022\024\n\014from_address\030\005 \001(\t\"" +
      "\026\n\024MsgCreateDIDResponse\"\223\001\n\014MsgUpdateDID" +
      "\022\013\n\003did\030\001 \001(\t\022-\n\010document\030\002 \001(\0132\033.panace" +
      "a.did.v2.DIDDocument\022\036\n\026verification_met" +
      "hod_id\030\003 \001(\t\022\021\n\tsignature\030\004 \001(\014\022\024\n\014from_" +
      "address\030\005 \001(\t\"\026\n\024MsgUpdateDIDResponse\"h\n" +
      "\020MsgDeactivateDID\022\013\n\003did\030\001 \001(\t\022\036\n\026verifi" +
      "cation_method_id\030\002 \001(\t\022\021\n\tsignature\030\003 \001(" +
      "\014\022\024\n\014from_address\030\004 \001(\t\"\032\n\030MsgDeactivate" +
      "DIDResponse2\204\002\n\003Msg\022O\n\tCreateDID\022\034.panac" +
      "ea.did.v2.MsgCreateDID\032$.panacea.did.v2." +
      "MsgCreateDIDResponse\022O\n\tUpdateDID\022\034.pana" +
      "cea.did.v2.MsgUpdateDID\032$.panacea.did.v2" +
      ".MsgUpdateDIDResponse\022[\n\rDeactivateDID\022 " +
      ".panacea.did.v2.MsgDeactivateDID\032(.panac" +
      "ea.did.v2.MsgDeactivateDIDResponseB0P\001Z," +
      "github.com/medibloc/panacea-core/x/did/t" +
      "ypesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.GoGoProtos.getDescriptor(),
          panacea.did.v2.Did.getDescriptor(),
        });
    internal_static_panacea_did_v2_MsgCreateDID_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_panacea_did_v2_MsgCreateDID_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_panacea_did_v2_MsgCreateDID_descriptor,
        new java.lang.String[] { "Did", "Document", "VerificationMethodId", "Signature", "FromAddress", });
    internal_static_panacea_did_v2_MsgCreateDIDResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_panacea_did_v2_MsgCreateDIDResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_panacea_did_v2_MsgCreateDIDResponse_descriptor,
        new java.lang.String[] { });
    internal_static_panacea_did_v2_MsgUpdateDID_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_panacea_did_v2_MsgUpdateDID_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_panacea_did_v2_MsgUpdateDID_descriptor,
        new java.lang.String[] { "Did", "Document", "VerificationMethodId", "Signature", "FromAddress", });
    internal_static_panacea_did_v2_MsgUpdateDIDResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_panacea_did_v2_MsgUpdateDIDResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_panacea_did_v2_MsgUpdateDIDResponse_descriptor,
        new java.lang.String[] { });
    internal_static_panacea_did_v2_MsgDeactivateDID_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_panacea_did_v2_MsgDeactivateDID_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_panacea_did_v2_MsgDeactivateDID_descriptor,
        new java.lang.String[] { "Did", "VerificationMethodId", "Signature", "FromAddress", });
    internal_static_panacea_did_v2_MsgDeactivateDIDResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_panacea_did_v2_MsgDeactivateDIDResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_panacea_did_v2_MsgDeactivateDIDResponse_descriptor,
        new java.lang.String[] { });
    com.google.protobuf.GoGoProtos.getDescriptor();
    panacea.did.v2.Did.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
