# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cosmostation' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'BinanceChain', :git => 'https://github.com/mh7821/SwiftBinanceChain.git'
  pod 'BitcoinKit', '~> 1.0.2'
  pod 'AlamofireImage', '~> 3.3'
  pod 'SQLite.swift', '~> 0.11.5'
  pod 'CryptoSwift'
  pod 'SwiftKeychainWrapper'
  pod 'Toast-Swift', '~> 4.0.0'
  pod 'Floaty', '~> 4.1.0'
  pod 'DropDown'
  pod 'QRCode'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

end

