# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cosmostation' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cosmostation
  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireImage', '~> 3.3'
  pod 'BitcoinKit'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'PromiseKit/CorePromise', '~> 6.8'
  pod 'SQLite.swift', '~> 0.11.5'
  pod 'CryptoSwift'
  pod 'SwiftKeychainWrapper'
  pod 'Toast-Swift', '~> 4.0.0'
  pod 'MBProgressHUD', '~> 1.1.0'
#  pod 'Toaster', '~> 2.1.1'

end
