# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cosmostation' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

#    pod 'BinanceChain', :git => 'https://github.com/binance-chain/swift-sdk.git'
    pod 'BinanceChain', :git => 'https://github.com/cosmostation/swift-sdk.git'
    pod 'WalletConnect', git: 'https://github.com/WalletConnect/swift-walletconnect-lib', branch: 'master'
    pod 'BitcoinKit', '~> 1.0.2'
    pod 'AlamofireImage', '~> 3.3'
    pod 'SQLite.swift', '~> 0.11.5'
#    pod 'CryptoSwift', '~> 1.5.0'
    pod 'SwiftKeychainWrapper'
    pod 'Toast-Swift', '~> 4.0.0'
    pod 'Floaty', '~> 4.1.0'
    pod 'DropDown'
    pod 'QRCode'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'NotificationBannerSwift', '2.0.1'
    pod 'gRPC-Swift', '~> 1.0.0'
    pod 'gRPC-Swift-Plugins'

end
