// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: gravity/v1/ethereum_signer.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// SignType defines messages that have been signed by an orchestrator
enum Gravity_V1_SignType: SwiftProtobuf.Enum {
  typealias RawValue = Int
  case unspecified // = 0
  case orchestratorSignedMultiSigUpdate // = 1
  case orchestratorSignedWithdrawBatch // = 2
  case UNRECOGNIZED(Int)

  init() {
    self = .unspecified
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .orchestratorSignedMultiSigUpdate
    case 2: self = .orchestratorSignedWithdrawBatch
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .orchestratorSignedMultiSigUpdate: return 1
    case .orchestratorSignedWithdrawBatch: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension Gravity_V1_SignType: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static var allCases: [Gravity_V1_SignType] = [
    .unspecified,
    .orchestratorSignedMultiSigUpdate,
    .orchestratorSignedWithdrawBatch,
  ]
}

#endif  // swift(>=4.2)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension Gravity_V1_SignType: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "SIGN_TYPE_UNSPECIFIED"),
    1: .same(proto: "SIGN_TYPE_ORCHESTRATOR_SIGNED_MULTI_SIG_UPDATE"),
    2: .same(proto: "SIGN_TYPE_ORCHESTRATOR_SIGNED_WITHDRAW_BATCH"),
  ]
}
