//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: record/tx.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Msg defines the oracle Msg service
///
/// Usage: instantiate `Irismod_Record_MsgClient`, then call methods of this protocol to make API calls.
internal protocol Irismod_Record_MsgClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Irismod_Record_MsgClientInterceptorFactoryProtocol? { get }

  func createRecord(
    _ request: Irismod_Record_MsgCreateRecord,
    callOptions: CallOptions?
  ) -> UnaryCall<Irismod_Record_MsgCreateRecord, Irismod_Record_MsgCreateRecordResponse>
}

extension Irismod_Record_MsgClientProtocol {
  internal var serviceName: String {
    return "irismod.record.Msg"
  }

  /// CreateRecord defines a method for creating a new record
  ///
  /// - Parameters:
  ///   - request: Request to send to CreateRecord.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func createRecord(
    _ request: Irismod_Record_MsgCreateRecord,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Irismod_Record_MsgCreateRecord, Irismod_Record_MsgCreateRecordResponse> {
    return self.makeUnaryCall(
      path: "/irismod.record.Msg/CreateRecord",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateRecordInterceptors() ?? []
    )
  }
}

internal protocol Irismod_Record_MsgClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'createRecord'.
  func makeCreateRecordInterceptors() -> [ClientInterceptor<Irismod_Record_MsgCreateRecord, Irismod_Record_MsgCreateRecordResponse>]
}

internal final class Irismod_Record_MsgClient: Irismod_Record_MsgClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Irismod_Record_MsgClientInterceptorFactoryProtocol?

  /// Creates a client for the irismod.record.Msg service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Irismod_Record_MsgClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// Msg defines the oracle Msg service
///
/// To build a server, implement a class that conforms to this protocol.
internal protocol Irismod_Record_MsgProvider: CallHandlerProvider {
  var interceptors: Irismod_Record_MsgServerInterceptorFactoryProtocol? { get }

  /// CreateRecord defines a method for creating a new record
  func createRecord(request: Irismod_Record_MsgCreateRecord, context: StatusOnlyCallContext) -> EventLoopFuture<Irismod_Record_MsgCreateRecordResponse>
}

extension Irismod_Record_MsgProvider {
  internal var serviceName: Substring { return "irismod.record.Msg" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "CreateRecord":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Irismod_Record_MsgCreateRecord>(),
        responseSerializer: ProtobufSerializer<Irismod_Record_MsgCreateRecordResponse>(),
        interceptors: self.interceptors?.makeCreateRecordInterceptors() ?? [],
        userFunction: self.createRecord(request:context:)
      )

    default:
      return nil
    }
  }
}

internal protocol Irismod_Record_MsgServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'createRecord'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeCreateRecordInterceptors() -> [ServerInterceptor<Irismod_Record_MsgCreateRecord, Irismod_Record_MsgCreateRecordResponse>]
}
