// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: em/authority/v1/authority.proto

package em.authority.v1;

public final class AuthorityOuterClass {
  private AuthorityOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AuthorityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:em.authority.v1.Authority)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string address = 1 [(.gogoproto.moretags) = "yaml:&#92;"address&#92;""];</code>
     * @return The address.
     */
    java.lang.String getAddress();
    /**
     * <code>string address = 1 [(.gogoproto.moretags) = "yaml:&#92;"address&#92;""];</code>
     * @return The bytes for address.
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <code>string former_address = 2 [(.gogoproto.moretags) = "yaml:&#92;"former_address&#92;""];</code>
     * @return The formerAddress.
     */
    java.lang.String getFormerAddress();
    /**
     * <code>string former_address = 2 [(.gogoproto.moretags) = "yaml:&#92;"former_address&#92;""];</code>
     * @return The bytes for formerAddress.
     */
    com.google.protobuf.ByteString
        getFormerAddressBytes();

    /**
     * <code>.google.protobuf.Timestamp last_modified = 3 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"last_modified&#92;"", (.gogoproto.stdtime) = true];</code>
     * @return Whether the lastModified field is set.
     */
    boolean hasLastModified();
    /**
     * <code>.google.protobuf.Timestamp last_modified = 3 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"last_modified&#92;"", (.gogoproto.stdtime) = true];</code>
     * @return The lastModified.
     */
    com.google.protobuf.Timestamp getLastModified();
    /**
     * <code>.google.protobuf.Timestamp last_modified = 3 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"last_modified&#92;"", (.gogoproto.stdtime) = true];</code>
     */
    com.google.protobuf.TimestampOrBuilder getLastModifiedOrBuilder();
  }
  /**
   * Protobuf type {@code em.authority.v1.Authority}
   */
  public static final class Authority extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:em.authority.v1.Authority)
      AuthorityOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Authority.newBuilder() to construct.
    private Authority(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Authority() {
      address_ = "";
      formerAddress_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Authority();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Authority(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              formerAddress_ = s;
              break;
            }
            case 26: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (lastModified_ != null) {
                subBuilder = lastModified_.toBuilder();
              }
              lastModified_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(lastModified_);
                lastModified_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return em.authority.v1.AuthorityOuterClass.internal_static_em_authority_v1_Authority_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return em.authority.v1.AuthorityOuterClass.internal_static_em_authority_v1_Authority_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              em.authority.v1.AuthorityOuterClass.Authority.class, em.authority.v1.AuthorityOuterClass.Authority.Builder.class);
    }

    public static final int ADDRESS_FIELD_NUMBER = 1;
    private volatile java.lang.Object address_;
    /**
     * <code>string address = 1 [(.gogoproto.moretags) = "yaml:&#92;"address&#92;""];</code>
     * @return The address.
     */
    @java.lang.Override
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <code>string address = 1 [(.gogoproto.moretags) = "yaml:&#92;"address&#92;""];</code>
     * @return The bytes for address.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FORMER_ADDRESS_FIELD_NUMBER = 2;
    private volatile java.lang.Object formerAddress_;
    /**
     * <code>string former_address = 2 [(.gogoproto.moretags) = "yaml:&#92;"former_address&#92;""];</code>
     * @return The formerAddress.
     */
    @java.lang.Override
    public java.lang.String getFormerAddress() {
      java.lang.Object ref = formerAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        formerAddress_ = s;
        return s;
      }
    }
    /**
     * <code>string former_address = 2 [(.gogoproto.moretags) = "yaml:&#92;"former_address&#92;""];</code>
     * @return The bytes for formerAddress.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFormerAddressBytes() {
      java.lang.Object ref = formerAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        formerAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LAST_MODIFIED_FIELD_NUMBER = 3;
    private com.google.protobuf.Timestamp lastModified_;
    /**
     * <code>.google.protobuf.Timestamp last_modified = 3 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"last_modified&#92;"", (.gogoproto.stdtime) = true];</code>
     * @return Whether the lastModified field is set.
     */
    @java.lang.Override
    public boolean hasLastModified() {
      return lastModified_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp last_modified = 3 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"last_modified&#92;"", (.gogoproto.stdtime) = true];</code>
     * @return The lastModified.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getLastModified() {
      return lastModified_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastModified_;
    }
    /**
     * <code>.google.protobuf.Timestamp last_modified = 3 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"last_modified&#92;"", (.gogoproto.stdtime) = true];</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getLastModifiedOrBuilder() {
      return getLastModified();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, address_);
      }
      if (!getFormerAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, formerAddress_);
      }
      if (lastModified_ != null) {
        output.writeMessage(3, getLastModified());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, address_);
      }
      if (!getFormerAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, formerAddress_);
      }
      if (lastModified_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getLastModified());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof em.authority.v1.AuthorityOuterClass.Authority)) {
        return super.equals(obj);
      }
      em.authority.v1.AuthorityOuterClass.Authority other = (em.authority.v1.AuthorityOuterClass.Authority) obj;

      if (!getAddress()
          .equals(other.getAddress())) return false;
      if (!getFormerAddress()
          .equals(other.getFormerAddress())) return false;
      if (hasLastModified() != other.hasLastModified()) return false;
      if (hasLastModified()) {
        if (!getLastModified()
            .equals(other.getLastModified())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (37 * hash) + FORMER_ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getFormerAddress().hashCode();
      if (hasLastModified()) {
        hash = (37 * hash) + LAST_MODIFIED_FIELD_NUMBER;
        hash = (53 * hash) + getLastModified().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static em.authority.v1.AuthorityOuterClass.Authority parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static em.authority.v1.AuthorityOuterClass.Authority parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static em.authority.v1.AuthorityOuterClass.Authority parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static em.authority.v1.AuthorityOuterClass.Authority parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static em.authority.v1.AuthorityOuterClass.Authority parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static em.authority.v1.AuthorityOuterClass.Authority parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static em.authority.v1.AuthorityOuterClass.Authority parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static em.authority.v1.AuthorityOuterClass.Authority parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static em.authority.v1.AuthorityOuterClass.Authority parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static em.authority.v1.AuthorityOuterClass.Authority parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static em.authority.v1.AuthorityOuterClass.Authority parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static em.authority.v1.AuthorityOuterClass.Authority parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(em.authority.v1.AuthorityOuterClass.Authority prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code em.authority.v1.Authority}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:em.authority.v1.Authority)
        em.authority.v1.AuthorityOuterClass.AuthorityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return em.authority.v1.AuthorityOuterClass.internal_static_em_authority_v1_Authority_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return em.authority.v1.AuthorityOuterClass.internal_static_em_authority_v1_Authority_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                em.authority.v1.AuthorityOuterClass.Authority.class, em.authority.v1.AuthorityOuterClass.Authority.Builder.class);
      }

      // Construct using em.authority.v1.AuthorityOuterClass.Authority.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        address_ = "";

        formerAddress_ = "";

        if (lastModifiedBuilder_ == null) {
          lastModified_ = null;
        } else {
          lastModified_ = null;
          lastModifiedBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return em.authority.v1.AuthorityOuterClass.internal_static_em_authority_v1_Authority_descriptor;
      }

      @java.lang.Override
      public em.authority.v1.AuthorityOuterClass.Authority getDefaultInstanceForType() {
        return em.authority.v1.AuthorityOuterClass.Authority.getDefaultInstance();
      }

      @java.lang.Override
      public em.authority.v1.AuthorityOuterClass.Authority build() {
        em.authority.v1.AuthorityOuterClass.Authority result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public em.authority.v1.AuthorityOuterClass.Authority buildPartial() {
        em.authority.v1.AuthorityOuterClass.Authority result = new em.authority.v1.AuthorityOuterClass.Authority(this);
        result.address_ = address_;
        result.formerAddress_ = formerAddress_;
        if (lastModifiedBuilder_ == null) {
          result.lastModified_ = lastModified_;
        } else {
          result.lastModified_ = lastModifiedBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof em.authority.v1.AuthorityOuterClass.Authority) {
          return mergeFrom((em.authority.v1.AuthorityOuterClass.Authority)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(em.authority.v1.AuthorityOuterClass.Authority other) {
        if (other == em.authority.v1.AuthorityOuterClass.Authority.getDefaultInstance()) return this;
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        if (!other.getFormerAddress().isEmpty()) {
          formerAddress_ = other.formerAddress_;
          onChanged();
        }
        if (other.hasLastModified()) {
          mergeLastModified(other.getLastModified());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        em.authority.v1.AuthorityOuterClass.Authority parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (em.authority.v1.AuthorityOuterClass.Authority) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <code>string address = 1 [(.gogoproto.moretags) = "yaml:&#92;"address&#92;""];</code>
       * @return The address.
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string address = 1 [(.gogoproto.moretags) = "yaml:&#92;"address&#92;""];</code>
       * @return The bytes for address.
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string address = 1 [(.gogoproto.moretags) = "yaml:&#92;"address&#92;""];</code>
       * @param value The address to set.
       * @return This builder for chaining.
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string address = 1 [(.gogoproto.moretags) = "yaml:&#92;"address&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string address = 1 [(.gogoproto.moretags) = "yaml:&#92;"address&#92;""];</code>
       * @param value The bytes for address to set.
       * @return This builder for chaining.
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        address_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object formerAddress_ = "";
      /**
       * <code>string former_address = 2 [(.gogoproto.moretags) = "yaml:&#92;"former_address&#92;""];</code>
       * @return The formerAddress.
       */
      public java.lang.String getFormerAddress() {
        java.lang.Object ref = formerAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          formerAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string former_address = 2 [(.gogoproto.moretags) = "yaml:&#92;"former_address&#92;""];</code>
       * @return The bytes for formerAddress.
       */
      public com.google.protobuf.ByteString
          getFormerAddressBytes() {
        java.lang.Object ref = formerAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          formerAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string former_address = 2 [(.gogoproto.moretags) = "yaml:&#92;"former_address&#92;""];</code>
       * @param value The formerAddress to set.
       * @return This builder for chaining.
       */
      public Builder setFormerAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        formerAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string former_address = 2 [(.gogoproto.moretags) = "yaml:&#92;"former_address&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearFormerAddress() {
        
        formerAddress_ = getDefaultInstance().getFormerAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string former_address = 2 [(.gogoproto.moretags) = "yaml:&#92;"former_address&#92;""];</code>
       * @param value The bytes for formerAddress to set.
       * @return This builder for chaining.
       */
      public Builder setFormerAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        formerAddress_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp lastModified_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> lastModifiedBuilder_;
      /**
       * <code>.google.protobuf.Timestamp last_modified = 3 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"last_modified&#92;"", (.gogoproto.stdtime) = true];</code>
       * @return Whether the lastModified field is set.
       */
      public boolean hasLastModified() {
        return lastModifiedBuilder_ != null || lastModified_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp last_modified = 3 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"last_modified&#92;"", (.gogoproto.stdtime) = true];</code>
       * @return The lastModified.
       */
      public com.google.protobuf.Timestamp getLastModified() {
        if (lastModifiedBuilder_ == null) {
          return lastModified_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastModified_;
        } else {
          return lastModifiedBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp last_modified = 3 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"last_modified&#92;"", (.gogoproto.stdtime) = true];</code>
       */
      public Builder setLastModified(com.google.protobuf.Timestamp value) {
        if (lastModifiedBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          lastModified_ = value;
          onChanged();
        } else {
          lastModifiedBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp last_modified = 3 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"last_modified&#92;"", (.gogoproto.stdtime) = true];</code>
       */
      public Builder setLastModified(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (lastModifiedBuilder_ == null) {
          lastModified_ = builderForValue.build();
          onChanged();
        } else {
          lastModifiedBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp last_modified = 3 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"last_modified&#92;"", (.gogoproto.stdtime) = true];</code>
       */
      public Builder mergeLastModified(com.google.protobuf.Timestamp value) {
        if (lastModifiedBuilder_ == null) {
          if (lastModified_ != null) {
            lastModified_ =
              com.google.protobuf.Timestamp.newBuilder(lastModified_).mergeFrom(value).buildPartial();
          } else {
            lastModified_ = value;
          }
          onChanged();
        } else {
          lastModifiedBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp last_modified = 3 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"last_modified&#92;"", (.gogoproto.stdtime) = true];</code>
       */
      public Builder clearLastModified() {
        if (lastModifiedBuilder_ == null) {
          lastModified_ = null;
          onChanged();
        } else {
          lastModified_ = null;
          lastModifiedBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp last_modified = 3 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"last_modified&#92;"", (.gogoproto.stdtime) = true];</code>
       */
      public com.google.protobuf.Timestamp.Builder getLastModifiedBuilder() {
        
        onChanged();
        return getLastModifiedFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp last_modified = 3 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"last_modified&#92;"", (.gogoproto.stdtime) = true];</code>
       */
      public com.google.protobuf.TimestampOrBuilder getLastModifiedOrBuilder() {
        if (lastModifiedBuilder_ != null) {
          return lastModifiedBuilder_.getMessageOrBuilder();
        } else {
          return lastModified_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : lastModified_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp last_modified = 3 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"last_modified&#92;"", (.gogoproto.stdtime) = true];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getLastModifiedFieldBuilder() {
        if (lastModifiedBuilder_ == null) {
          lastModifiedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getLastModified(),
                  getParentForChildren(),
                  isClean());
          lastModified_ = null;
        }
        return lastModifiedBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:em.authority.v1.Authority)
    }

    // @@protoc_insertion_point(class_scope:em.authority.v1.Authority)
    private static final em.authority.v1.AuthorityOuterClass.Authority DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new em.authority.v1.AuthorityOuterClass.Authority();
    }

    public static em.authority.v1.AuthorityOuterClass.Authority getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Authority>
        PARSER = new com.google.protobuf.AbstractParser<Authority>() {
      @java.lang.Override
      public Authority parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Authority(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Authority> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Authority> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public em.authority.v1.AuthorityOuterClass.Authority getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GasPricesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:em.authority.v1.GasPrices)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .cosmos.base.v1beta1.DecCoin minimum = 1 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"minimum&#92;"", (.gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.DecCoins"];</code>
     */
    java.util.List<cosmos.base.v1beta1.CoinOuterClass.DecCoin> 
        getMinimumList();
    /**
     * <code>repeated .cosmos.base.v1beta1.DecCoin minimum = 1 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"minimum&#92;"", (.gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.DecCoins"];</code>
     */
    cosmos.base.v1beta1.CoinOuterClass.DecCoin getMinimum(int index);
    /**
     * <code>repeated .cosmos.base.v1beta1.DecCoin minimum = 1 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"minimum&#92;"", (.gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.DecCoins"];</code>
     */
    int getMinimumCount();
    /**
     * <code>repeated .cosmos.base.v1beta1.DecCoin minimum = 1 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"minimum&#92;"", (.gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.DecCoins"];</code>
     */
    java.util.List<? extends cosmos.base.v1beta1.CoinOuterClass.DecCoinOrBuilder> 
        getMinimumOrBuilderList();
    /**
     * <code>repeated .cosmos.base.v1beta1.DecCoin minimum = 1 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"minimum&#92;"", (.gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.DecCoins"];</code>
     */
    cosmos.base.v1beta1.CoinOuterClass.DecCoinOrBuilder getMinimumOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code em.authority.v1.GasPrices}
   */
  public static final class GasPrices extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:em.authority.v1.GasPrices)
      GasPricesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GasPrices.newBuilder() to construct.
    private GasPrices(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GasPrices() {
      minimum_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GasPrices();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GasPrices(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                minimum_ = new java.util.ArrayList<cosmos.base.v1beta1.CoinOuterClass.DecCoin>();
                mutable_bitField0_ |= 0x00000001;
              }
              minimum_.add(
                  input.readMessage(cosmos.base.v1beta1.CoinOuterClass.DecCoin.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          minimum_ = java.util.Collections.unmodifiableList(minimum_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return em.authority.v1.AuthorityOuterClass.internal_static_em_authority_v1_GasPrices_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return em.authority.v1.AuthorityOuterClass.internal_static_em_authority_v1_GasPrices_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              em.authority.v1.AuthorityOuterClass.GasPrices.class, em.authority.v1.AuthorityOuterClass.GasPrices.Builder.class);
    }

    public static final int MINIMUM_FIELD_NUMBER = 1;
    private java.util.List<cosmos.base.v1beta1.CoinOuterClass.DecCoin> minimum_;
    /**
     * <code>repeated .cosmos.base.v1beta1.DecCoin minimum = 1 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"minimum&#92;"", (.gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.DecCoins"];</code>
     */
    @java.lang.Override
    public java.util.List<cosmos.base.v1beta1.CoinOuterClass.DecCoin> getMinimumList() {
      return minimum_;
    }
    /**
     * <code>repeated .cosmos.base.v1beta1.DecCoin minimum = 1 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"minimum&#92;"", (.gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.DecCoins"];</code>
     */
    @java.lang.Override
    public java.util.List<? extends cosmos.base.v1beta1.CoinOuterClass.DecCoinOrBuilder> 
        getMinimumOrBuilderList() {
      return minimum_;
    }
    /**
     * <code>repeated .cosmos.base.v1beta1.DecCoin minimum = 1 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"minimum&#92;"", (.gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.DecCoins"];</code>
     */
    @java.lang.Override
    public int getMinimumCount() {
      return minimum_.size();
    }
    /**
     * <code>repeated .cosmos.base.v1beta1.DecCoin minimum = 1 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"minimum&#92;"", (.gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.DecCoins"];</code>
     */
    @java.lang.Override
    public cosmos.base.v1beta1.CoinOuterClass.DecCoin getMinimum(int index) {
      return minimum_.get(index);
    }
    /**
     * <code>repeated .cosmos.base.v1beta1.DecCoin minimum = 1 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"minimum&#92;"", (.gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.DecCoins"];</code>
     */
    @java.lang.Override
    public cosmos.base.v1beta1.CoinOuterClass.DecCoinOrBuilder getMinimumOrBuilder(
        int index) {
      return minimum_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < minimum_.size(); i++) {
        output.writeMessage(1, minimum_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < minimum_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, minimum_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof em.authority.v1.AuthorityOuterClass.GasPrices)) {
        return super.equals(obj);
      }
      em.authority.v1.AuthorityOuterClass.GasPrices other = (em.authority.v1.AuthorityOuterClass.GasPrices) obj;

      if (!getMinimumList()
          .equals(other.getMinimumList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getMinimumCount() > 0) {
        hash = (37 * hash) + MINIMUM_FIELD_NUMBER;
        hash = (53 * hash) + getMinimumList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static em.authority.v1.AuthorityOuterClass.GasPrices parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static em.authority.v1.AuthorityOuterClass.GasPrices parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static em.authority.v1.AuthorityOuterClass.GasPrices parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static em.authority.v1.AuthorityOuterClass.GasPrices parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static em.authority.v1.AuthorityOuterClass.GasPrices parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static em.authority.v1.AuthorityOuterClass.GasPrices parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static em.authority.v1.AuthorityOuterClass.GasPrices parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static em.authority.v1.AuthorityOuterClass.GasPrices parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static em.authority.v1.AuthorityOuterClass.GasPrices parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static em.authority.v1.AuthorityOuterClass.GasPrices parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static em.authority.v1.AuthorityOuterClass.GasPrices parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static em.authority.v1.AuthorityOuterClass.GasPrices parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(em.authority.v1.AuthorityOuterClass.GasPrices prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code em.authority.v1.GasPrices}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:em.authority.v1.GasPrices)
        em.authority.v1.AuthorityOuterClass.GasPricesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return em.authority.v1.AuthorityOuterClass.internal_static_em_authority_v1_GasPrices_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return em.authority.v1.AuthorityOuterClass.internal_static_em_authority_v1_GasPrices_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                em.authority.v1.AuthorityOuterClass.GasPrices.class, em.authority.v1.AuthorityOuterClass.GasPrices.Builder.class);
      }

      // Construct using em.authority.v1.AuthorityOuterClass.GasPrices.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMinimumFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (minimumBuilder_ == null) {
          minimum_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          minimumBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return em.authority.v1.AuthorityOuterClass.internal_static_em_authority_v1_GasPrices_descriptor;
      }

      @java.lang.Override
      public em.authority.v1.AuthorityOuterClass.GasPrices getDefaultInstanceForType() {
        return em.authority.v1.AuthorityOuterClass.GasPrices.getDefaultInstance();
      }

      @java.lang.Override
      public em.authority.v1.AuthorityOuterClass.GasPrices build() {
        em.authority.v1.AuthorityOuterClass.GasPrices result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public em.authority.v1.AuthorityOuterClass.GasPrices buildPartial() {
        em.authority.v1.AuthorityOuterClass.GasPrices result = new em.authority.v1.AuthorityOuterClass.GasPrices(this);
        int from_bitField0_ = bitField0_;
        if (minimumBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            minimum_ = java.util.Collections.unmodifiableList(minimum_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.minimum_ = minimum_;
        } else {
          result.minimum_ = minimumBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof em.authority.v1.AuthorityOuterClass.GasPrices) {
          return mergeFrom((em.authority.v1.AuthorityOuterClass.GasPrices)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(em.authority.v1.AuthorityOuterClass.GasPrices other) {
        if (other == em.authority.v1.AuthorityOuterClass.GasPrices.getDefaultInstance()) return this;
        if (minimumBuilder_ == null) {
          if (!other.minimum_.isEmpty()) {
            if (minimum_.isEmpty()) {
              minimum_ = other.minimum_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMinimumIsMutable();
              minimum_.addAll(other.minimum_);
            }
            onChanged();
          }
        } else {
          if (!other.minimum_.isEmpty()) {
            if (minimumBuilder_.isEmpty()) {
              minimumBuilder_.dispose();
              minimumBuilder_ = null;
              minimum_ = other.minimum_;
              bitField0_ = (bitField0_ & ~0x00000001);
              minimumBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMinimumFieldBuilder() : null;
            } else {
              minimumBuilder_.addAllMessages(other.minimum_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        em.authority.v1.AuthorityOuterClass.GasPrices parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (em.authority.v1.AuthorityOuterClass.GasPrices) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<cosmos.base.v1beta1.CoinOuterClass.DecCoin> minimum_ =
        java.util.Collections.emptyList();
      private void ensureMinimumIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          minimum_ = new java.util.ArrayList<cosmos.base.v1beta1.CoinOuterClass.DecCoin>(minimum_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          cosmos.base.v1beta1.CoinOuterClass.DecCoin, cosmos.base.v1beta1.CoinOuterClass.DecCoin.Builder, cosmos.base.v1beta1.CoinOuterClass.DecCoinOrBuilder> minimumBuilder_;

      /**
       * <code>repeated .cosmos.base.v1beta1.DecCoin minimum = 1 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"minimum&#92;"", (.gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.DecCoins"];</code>
       */
      public java.util.List<cosmos.base.v1beta1.CoinOuterClass.DecCoin> getMinimumList() {
        if (minimumBuilder_ == null) {
          return java.util.Collections.unmodifiableList(minimum_);
        } else {
          return minimumBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .cosmos.base.v1beta1.DecCoin minimum = 1 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"minimum&#92;"", (.gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.DecCoins"];</code>
       */
      public int getMinimumCount() {
        if (minimumBuilder_ == null) {
          return minimum_.size();
        } else {
          return minimumBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .cosmos.base.v1beta1.DecCoin minimum = 1 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"minimum&#92;"", (.gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.DecCoins"];</code>
       */
      public cosmos.base.v1beta1.CoinOuterClass.DecCoin getMinimum(int index) {
        if (minimumBuilder_ == null) {
          return minimum_.get(index);
        } else {
          return minimumBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .cosmos.base.v1beta1.DecCoin minimum = 1 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"minimum&#92;"", (.gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.DecCoins"];</code>
       */
      public Builder setMinimum(
          int index, cosmos.base.v1beta1.CoinOuterClass.DecCoin value) {
        if (minimumBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMinimumIsMutable();
          minimum_.set(index, value);
          onChanged();
        } else {
          minimumBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .cosmos.base.v1beta1.DecCoin minimum = 1 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"minimum&#92;"", (.gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.DecCoins"];</code>
       */
      public Builder setMinimum(
          int index, cosmos.base.v1beta1.CoinOuterClass.DecCoin.Builder builderForValue) {
        if (minimumBuilder_ == null) {
          ensureMinimumIsMutable();
          minimum_.set(index, builderForValue.build());
          onChanged();
        } else {
          minimumBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cosmos.base.v1beta1.DecCoin minimum = 1 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"minimum&#92;"", (.gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.DecCoins"];</code>
       */
      public Builder addMinimum(cosmos.base.v1beta1.CoinOuterClass.DecCoin value) {
        if (minimumBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMinimumIsMutable();
          minimum_.add(value);
          onChanged();
        } else {
          minimumBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .cosmos.base.v1beta1.DecCoin minimum = 1 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"minimum&#92;"", (.gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.DecCoins"];</code>
       */
      public Builder addMinimum(
          int index, cosmos.base.v1beta1.CoinOuterClass.DecCoin value) {
        if (minimumBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMinimumIsMutable();
          minimum_.add(index, value);
          onChanged();
        } else {
          minimumBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .cosmos.base.v1beta1.DecCoin minimum = 1 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"minimum&#92;"", (.gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.DecCoins"];</code>
       */
      public Builder addMinimum(
          cosmos.base.v1beta1.CoinOuterClass.DecCoin.Builder builderForValue) {
        if (minimumBuilder_ == null) {
          ensureMinimumIsMutable();
          minimum_.add(builderForValue.build());
          onChanged();
        } else {
          minimumBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cosmos.base.v1beta1.DecCoin minimum = 1 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"minimum&#92;"", (.gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.DecCoins"];</code>
       */
      public Builder addMinimum(
          int index, cosmos.base.v1beta1.CoinOuterClass.DecCoin.Builder builderForValue) {
        if (minimumBuilder_ == null) {
          ensureMinimumIsMutable();
          minimum_.add(index, builderForValue.build());
          onChanged();
        } else {
          minimumBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cosmos.base.v1beta1.DecCoin minimum = 1 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"minimum&#92;"", (.gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.DecCoins"];</code>
       */
      public Builder addAllMinimum(
          java.lang.Iterable<? extends cosmos.base.v1beta1.CoinOuterClass.DecCoin> values) {
        if (minimumBuilder_ == null) {
          ensureMinimumIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, minimum_);
          onChanged();
        } else {
          minimumBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .cosmos.base.v1beta1.DecCoin minimum = 1 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"minimum&#92;"", (.gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.DecCoins"];</code>
       */
      public Builder clearMinimum() {
        if (minimumBuilder_ == null) {
          minimum_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          minimumBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .cosmos.base.v1beta1.DecCoin minimum = 1 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"minimum&#92;"", (.gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.DecCoins"];</code>
       */
      public Builder removeMinimum(int index) {
        if (minimumBuilder_ == null) {
          ensureMinimumIsMutable();
          minimum_.remove(index);
          onChanged();
        } else {
          minimumBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .cosmos.base.v1beta1.DecCoin minimum = 1 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"minimum&#92;"", (.gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.DecCoins"];</code>
       */
      public cosmos.base.v1beta1.CoinOuterClass.DecCoin.Builder getMinimumBuilder(
          int index) {
        return getMinimumFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .cosmos.base.v1beta1.DecCoin minimum = 1 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"minimum&#92;"", (.gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.DecCoins"];</code>
       */
      public cosmos.base.v1beta1.CoinOuterClass.DecCoinOrBuilder getMinimumOrBuilder(
          int index) {
        if (minimumBuilder_ == null) {
          return minimum_.get(index);  } else {
          return minimumBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .cosmos.base.v1beta1.DecCoin minimum = 1 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"minimum&#92;"", (.gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.DecCoins"];</code>
       */
      public java.util.List<? extends cosmos.base.v1beta1.CoinOuterClass.DecCoinOrBuilder> 
           getMinimumOrBuilderList() {
        if (minimumBuilder_ != null) {
          return minimumBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(minimum_);
        }
      }
      /**
       * <code>repeated .cosmos.base.v1beta1.DecCoin minimum = 1 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"minimum&#92;"", (.gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.DecCoins"];</code>
       */
      public cosmos.base.v1beta1.CoinOuterClass.DecCoin.Builder addMinimumBuilder() {
        return getMinimumFieldBuilder().addBuilder(
            cosmos.base.v1beta1.CoinOuterClass.DecCoin.getDefaultInstance());
      }
      /**
       * <code>repeated .cosmos.base.v1beta1.DecCoin minimum = 1 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"minimum&#92;"", (.gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.DecCoins"];</code>
       */
      public cosmos.base.v1beta1.CoinOuterClass.DecCoin.Builder addMinimumBuilder(
          int index) {
        return getMinimumFieldBuilder().addBuilder(
            index, cosmos.base.v1beta1.CoinOuterClass.DecCoin.getDefaultInstance());
      }
      /**
       * <code>repeated .cosmos.base.v1beta1.DecCoin minimum = 1 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"minimum&#92;"", (.gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.DecCoins"];</code>
       */
      public java.util.List<cosmos.base.v1beta1.CoinOuterClass.DecCoin.Builder> 
           getMinimumBuilderList() {
        return getMinimumFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          cosmos.base.v1beta1.CoinOuterClass.DecCoin, cosmos.base.v1beta1.CoinOuterClass.DecCoin.Builder, cosmos.base.v1beta1.CoinOuterClass.DecCoinOrBuilder> 
          getMinimumFieldBuilder() {
        if (minimumBuilder_ == null) {
          minimumBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              cosmos.base.v1beta1.CoinOuterClass.DecCoin, cosmos.base.v1beta1.CoinOuterClass.DecCoin.Builder, cosmos.base.v1beta1.CoinOuterClass.DecCoinOrBuilder>(
                  minimum_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          minimum_ = null;
        }
        return minimumBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:em.authority.v1.GasPrices)
    }

    // @@protoc_insertion_point(class_scope:em.authority.v1.GasPrices)
    private static final em.authority.v1.AuthorityOuterClass.GasPrices DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new em.authority.v1.AuthorityOuterClass.GasPrices();
    }

    public static em.authority.v1.AuthorityOuterClass.GasPrices getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GasPrices>
        PARSER = new com.google.protobuf.AbstractParser<GasPrices>() {
      @java.lang.Override
      public GasPrices parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GasPrices(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GasPrices> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GasPrices> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public em.authority.v1.AuthorityOuterClass.GasPrices getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_em_authority_v1_Authority_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_em_authority_v1_Authority_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_em_authority_v1_GasPrices_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_em_authority_v1_GasPrices_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037em/authority/v1/authority.proto\022\017em.au" +
      "thority.v1\032\024gogoproto/gogo.proto\032\036cosmos" +
      "/base/v1beta1/coin.proto\032\037google/protobu" +
      "f/timestamp.proto\"\270\001\n\tAuthority\022#\n\007addre" +
      "ss\030\001 \001(\tB\022\362\336\037\016yaml:\"address\"\0221\n\016former_a" +
      "ddress\030\002 \001(\tB\031\362\336\037\025yaml:\"former_address\"\022" +
      "S\n\rlast_modified\030\003 \001(\0132\032.google.protobuf" +
      ".TimestampB \362\336\037\024yaml:\"last_modified\"\220\337\037\001" +
      "\310\336\037\000\"\201\001\n\tGasPrices\022t\n\007minimum\030\001 \003(\0132\034.co" +
      "smos.base.v1beta1.DecCoinBE\362\336\037\016yaml:\"min" +
      "imum\"\252\337\037+github.com/cosmos/cosmos-sdk/ty" +
      "pes.DecCoins\310\336\037\000B0Z.github.com/e-money/e" +
      "m-ledger/x/authority/typesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf2.GoGoProtos.getDescriptor(),
          cosmos.base.v1beta1.CoinOuterClass.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_em_authority_v1_Authority_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_em_authority_v1_Authority_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_em_authority_v1_Authority_descriptor,
        new java.lang.String[] { "Address", "FormerAddress", "LastModified", });
    internal_static_em_authority_v1_GasPrices_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_em_authority_v1_GasPrices_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_em_authority_v1_GasPrices_descriptor,
        new java.lang.String[] { "Minimum", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf2.GoGoProtos.castrepeated);
    registry.add(com.google.protobuf2.GoGoProtos.moretags);
    registry.add(com.google.protobuf2.GoGoProtos.nullable);
    registry.add(com.google.protobuf2.GoGoProtos.stdtime);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf2.GoGoProtos.getDescriptor();
    cosmos.base.v1beta1.CoinOuterClass.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
