// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: osmosis/store/v1beta1/tree.proto

package osmosis.store.v1beta1;

public final class Tree {
  private Tree() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NodeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:osmosis.store.v1beta1.Node)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .osmosis.store.v1beta1.Child children = 1;</code>
     */
    java.util.List<osmosis.store.v1beta1.Tree.Child> 
        getChildrenList();
    /**
     * <code>repeated .osmosis.store.v1beta1.Child children = 1;</code>
     */
    osmosis.store.v1beta1.Tree.Child getChildren(int index);
    /**
     * <code>repeated .osmosis.store.v1beta1.Child children = 1;</code>
     */
    int getChildrenCount();
    /**
     * <code>repeated .osmosis.store.v1beta1.Child children = 1;</code>
     */
    java.util.List<? extends osmosis.store.v1beta1.Tree.ChildOrBuilder> 
        getChildrenOrBuilderList();
    /**
     * <code>repeated .osmosis.store.v1beta1.Child children = 1;</code>
     */
    osmosis.store.v1beta1.Tree.ChildOrBuilder getChildrenOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code osmosis.store.v1beta1.Node}
   */
  public static final class Node extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:osmosis.store.v1beta1.Node)
      NodeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Node.newBuilder() to construct.
    private Node(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Node() {
      children_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Node();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Node(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                children_ = new java.util.ArrayList<osmosis.store.v1beta1.Tree.Child>();
                mutable_bitField0_ |= 0x00000001;
              }
              children_.add(
                  input.readMessage(osmosis.store.v1beta1.Tree.Child.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          children_ = java.util.Collections.unmodifiableList(children_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return osmosis.store.v1beta1.Tree.internal_static_osmosis_store_v1beta1_Node_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return osmosis.store.v1beta1.Tree.internal_static_osmosis_store_v1beta1_Node_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              osmosis.store.v1beta1.Tree.Node.class, osmosis.store.v1beta1.Tree.Node.Builder.class);
    }

    public static final int CHILDREN_FIELD_NUMBER = 1;
    private java.util.List<osmosis.store.v1beta1.Tree.Child> children_;
    /**
     * <code>repeated .osmosis.store.v1beta1.Child children = 1;</code>
     */
    @java.lang.Override
    public java.util.List<osmosis.store.v1beta1.Tree.Child> getChildrenList() {
      return children_;
    }
    /**
     * <code>repeated .osmosis.store.v1beta1.Child children = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends osmosis.store.v1beta1.Tree.ChildOrBuilder> 
        getChildrenOrBuilderList() {
      return children_;
    }
    /**
     * <code>repeated .osmosis.store.v1beta1.Child children = 1;</code>
     */
    @java.lang.Override
    public int getChildrenCount() {
      return children_.size();
    }
    /**
     * <code>repeated .osmosis.store.v1beta1.Child children = 1;</code>
     */
    @java.lang.Override
    public osmosis.store.v1beta1.Tree.Child getChildren(int index) {
      return children_.get(index);
    }
    /**
     * <code>repeated .osmosis.store.v1beta1.Child children = 1;</code>
     */
    @java.lang.Override
    public osmosis.store.v1beta1.Tree.ChildOrBuilder getChildrenOrBuilder(
        int index) {
      return children_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < children_.size(); i++) {
        output.writeMessage(1, children_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < children_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, children_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof osmosis.store.v1beta1.Tree.Node)) {
        return super.equals(obj);
      }
      osmosis.store.v1beta1.Tree.Node other = (osmosis.store.v1beta1.Tree.Node) obj;

      if (!getChildrenList()
          .equals(other.getChildrenList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getChildrenCount() > 0) {
        hash = (37 * hash) + CHILDREN_FIELD_NUMBER;
        hash = (53 * hash) + getChildrenList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static osmosis.store.v1beta1.Tree.Node parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static osmosis.store.v1beta1.Tree.Node parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static osmosis.store.v1beta1.Tree.Node parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static osmosis.store.v1beta1.Tree.Node parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static osmosis.store.v1beta1.Tree.Node parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static osmosis.store.v1beta1.Tree.Node parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static osmosis.store.v1beta1.Tree.Node parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static osmosis.store.v1beta1.Tree.Node parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static osmosis.store.v1beta1.Tree.Node parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static osmosis.store.v1beta1.Tree.Node parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static osmosis.store.v1beta1.Tree.Node parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static osmosis.store.v1beta1.Tree.Node parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(osmosis.store.v1beta1.Tree.Node prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code osmosis.store.v1beta1.Node}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:osmosis.store.v1beta1.Node)
        osmosis.store.v1beta1.Tree.NodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return osmosis.store.v1beta1.Tree.internal_static_osmosis_store_v1beta1_Node_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return osmosis.store.v1beta1.Tree.internal_static_osmosis_store_v1beta1_Node_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                osmosis.store.v1beta1.Tree.Node.class, osmosis.store.v1beta1.Tree.Node.Builder.class);
      }

      // Construct using osmosis.store.v1beta1.Tree.Node.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getChildrenFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (childrenBuilder_ == null) {
          children_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          childrenBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return osmosis.store.v1beta1.Tree.internal_static_osmosis_store_v1beta1_Node_descriptor;
      }

      @java.lang.Override
      public osmosis.store.v1beta1.Tree.Node getDefaultInstanceForType() {
        return osmosis.store.v1beta1.Tree.Node.getDefaultInstance();
      }

      @java.lang.Override
      public osmosis.store.v1beta1.Tree.Node build() {
        osmosis.store.v1beta1.Tree.Node result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public osmosis.store.v1beta1.Tree.Node buildPartial() {
        osmosis.store.v1beta1.Tree.Node result = new osmosis.store.v1beta1.Tree.Node(this);
        int from_bitField0_ = bitField0_;
        if (childrenBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            children_ = java.util.Collections.unmodifiableList(children_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.children_ = children_;
        } else {
          result.children_ = childrenBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof osmosis.store.v1beta1.Tree.Node) {
          return mergeFrom((osmosis.store.v1beta1.Tree.Node)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(osmosis.store.v1beta1.Tree.Node other) {
        if (other == osmosis.store.v1beta1.Tree.Node.getDefaultInstance()) return this;
        if (childrenBuilder_ == null) {
          if (!other.children_.isEmpty()) {
            if (children_.isEmpty()) {
              children_ = other.children_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureChildrenIsMutable();
              children_.addAll(other.children_);
            }
            onChanged();
          }
        } else {
          if (!other.children_.isEmpty()) {
            if (childrenBuilder_.isEmpty()) {
              childrenBuilder_.dispose();
              childrenBuilder_ = null;
              children_ = other.children_;
              bitField0_ = (bitField0_ & ~0x00000001);
              childrenBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getChildrenFieldBuilder() : null;
            } else {
              childrenBuilder_.addAllMessages(other.children_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        osmosis.store.v1beta1.Tree.Node parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (osmosis.store.v1beta1.Tree.Node) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<osmosis.store.v1beta1.Tree.Child> children_ =
        java.util.Collections.emptyList();
      private void ensureChildrenIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          children_ = new java.util.ArrayList<osmosis.store.v1beta1.Tree.Child>(children_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          osmosis.store.v1beta1.Tree.Child, osmosis.store.v1beta1.Tree.Child.Builder, osmosis.store.v1beta1.Tree.ChildOrBuilder> childrenBuilder_;

      /**
       * <code>repeated .osmosis.store.v1beta1.Child children = 1;</code>
       */
      public java.util.List<osmosis.store.v1beta1.Tree.Child> getChildrenList() {
        if (childrenBuilder_ == null) {
          return java.util.Collections.unmodifiableList(children_);
        } else {
          return childrenBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .osmosis.store.v1beta1.Child children = 1;</code>
       */
      public int getChildrenCount() {
        if (childrenBuilder_ == null) {
          return children_.size();
        } else {
          return childrenBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .osmosis.store.v1beta1.Child children = 1;</code>
       */
      public osmosis.store.v1beta1.Tree.Child getChildren(int index) {
        if (childrenBuilder_ == null) {
          return children_.get(index);
        } else {
          return childrenBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .osmosis.store.v1beta1.Child children = 1;</code>
       */
      public Builder setChildren(
          int index, osmosis.store.v1beta1.Tree.Child value) {
        if (childrenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChildrenIsMutable();
          children_.set(index, value);
          onChanged();
        } else {
          childrenBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .osmosis.store.v1beta1.Child children = 1;</code>
       */
      public Builder setChildren(
          int index, osmosis.store.v1beta1.Tree.Child.Builder builderForValue) {
        if (childrenBuilder_ == null) {
          ensureChildrenIsMutable();
          children_.set(index, builderForValue.build());
          onChanged();
        } else {
          childrenBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .osmosis.store.v1beta1.Child children = 1;</code>
       */
      public Builder addChildren(osmosis.store.v1beta1.Tree.Child value) {
        if (childrenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChildrenIsMutable();
          children_.add(value);
          onChanged();
        } else {
          childrenBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .osmosis.store.v1beta1.Child children = 1;</code>
       */
      public Builder addChildren(
          int index, osmosis.store.v1beta1.Tree.Child value) {
        if (childrenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChildrenIsMutable();
          children_.add(index, value);
          onChanged();
        } else {
          childrenBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .osmosis.store.v1beta1.Child children = 1;</code>
       */
      public Builder addChildren(
          osmosis.store.v1beta1.Tree.Child.Builder builderForValue) {
        if (childrenBuilder_ == null) {
          ensureChildrenIsMutable();
          children_.add(builderForValue.build());
          onChanged();
        } else {
          childrenBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .osmosis.store.v1beta1.Child children = 1;</code>
       */
      public Builder addChildren(
          int index, osmosis.store.v1beta1.Tree.Child.Builder builderForValue) {
        if (childrenBuilder_ == null) {
          ensureChildrenIsMutable();
          children_.add(index, builderForValue.build());
          onChanged();
        } else {
          childrenBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .osmosis.store.v1beta1.Child children = 1;</code>
       */
      public Builder addAllChildren(
          java.lang.Iterable<? extends osmosis.store.v1beta1.Tree.Child> values) {
        if (childrenBuilder_ == null) {
          ensureChildrenIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, children_);
          onChanged();
        } else {
          childrenBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .osmosis.store.v1beta1.Child children = 1;</code>
       */
      public Builder clearChildren() {
        if (childrenBuilder_ == null) {
          children_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          childrenBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .osmosis.store.v1beta1.Child children = 1;</code>
       */
      public Builder removeChildren(int index) {
        if (childrenBuilder_ == null) {
          ensureChildrenIsMutable();
          children_.remove(index);
          onChanged();
        } else {
          childrenBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .osmosis.store.v1beta1.Child children = 1;</code>
       */
      public osmosis.store.v1beta1.Tree.Child.Builder getChildrenBuilder(
          int index) {
        return getChildrenFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .osmosis.store.v1beta1.Child children = 1;</code>
       */
      public osmosis.store.v1beta1.Tree.ChildOrBuilder getChildrenOrBuilder(
          int index) {
        if (childrenBuilder_ == null) {
          return children_.get(index);  } else {
          return childrenBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .osmosis.store.v1beta1.Child children = 1;</code>
       */
      public java.util.List<? extends osmosis.store.v1beta1.Tree.ChildOrBuilder> 
           getChildrenOrBuilderList() {
        if (childrenBuilder_ != null) {
          return childrenBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(children_);
        }
      }
      /**
       * <code>repeated .osmosis.store.v1beta1.Child children = 1;</code>
       */
      public osmosis.store.v1beta1.Tree.Child.Builder addChildrenBuilder() {
        return getChildrenFieldBuilder().addBuilder(
            osmosis.store.v1beta1.Tree.Child.getDefaultInstance());
      }
      /**
       * <code>repeated .osmosis.store.v1beta1.Child children = 1;</code>
       */
      public osmosis.store.v1beta1.Tree.Child.Builder addChildrenBuilder(
          int index) {
        return getChildrenFieldBuilder().addBuilder(
            index, osmosis.store.v1beta1.Tree.Child.getDefaultInstance());
      }
      /**
       * <code>repeated .osmosis.store.v1beta1.Child children = 1;</code>
       */
      public java.util.List<osmosis.store.v1beta1.Tree.Child.Builder> 
           getChildrenBuilderList() {
        return getChildrenFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          osmosis.store.v1beta1.Tree.Child, osmosis.store.v1beta1.Tree.Child.Builder, osmosis.store.v1beta1.Tree.ChildOrBuilder> 
          getChildrenFieldBuilder() {
        if (childrenBuilder_ == null) {
          childrenBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              osmosis.store.v1beta1.Tree.Child, osmosis.store.v1beta1.Tree.Child.Builder, osmosis.store.v1beta1.Tree.ChildOrBuilder>(
                  children_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          children_ = null;
        }
        return childrenBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:osmosis.store.v1beta1.Node)
    }

    // @@protoc_insertion_point(class_scope:osmosis.store.v1beta1.Node)
    private static final osmosis.store.v1beta1.Tree.Node DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new osmosis.store.v1beta1.Tree.Node();
    }

    public static osmosis.store.v1beta1.Tree.Node getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Node>
        PARSER = new com.google.protobuf.AbstractParser<Node>() {
      @java.lang.Override
      public Node parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Node(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Node> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Node> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public osmosis.store.v1beta1.Tree.Node getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ChildOrBuilder extends
      // @@protoc_insertion_point(interface_extends:osmosis.store.v1beta1.Child)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes index = 1;</code>
     * @return The index.
     */
    com.google.protobuf.ByteString getIndex();

    /**
     * <code>string accumulation = 2 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int"];</code>
     * @return The accumulation.
     */
    java.lang.String getAccumulation();
    /**
     * <code>string accumulation = 2 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int"];</code>
     * @return The bytes for accumulation.
     */
    com.google.protobuf.ByteString
        getAccumulationBytes();
  }
  /**
   * Protobuf type {@code osmosis.store.v1beta1.Child}
   */
  public static final class Child extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:osmosis.store.v1beta1.Child)
      ChildOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Child.newBuilder() to construct.
    private Child(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Child() {
      index_ = com.google.protobuf.ByteString.EMPTY;
      accumulation_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Child();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Child(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              index_ = input.readBytes();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              accumulation_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return osmosis.store.v1beta1.Tree.internal_static_osmosis_store_v1beta1_Child_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return osmosis.store.v1beta1.Tree.internal_static_osmosis_store_v1beta1_Child_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              osmosis.store.v1beta1.Tree.Child.class, osmosis.store.v1beta1.Tree.Child.Builder.class);
    }

    public static final int INDEX_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString index_;
    /**
     * <code>bytes index = 1;</code>
     * @return The index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getIndex() {
      return index_;
    }

    public static final int ACCUMULATION_FIELD_NUMBER = 2;
    private volatile java.lang.Object accumulation_;
    /**
     * <code>string accumulation = 2 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int"];</code>
     * @return The accumulation.
     */
    @java.lang.Override
    public java.lang.String getAccumulation() {
      java.lang.Object ref = accumulation_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accumulation_ = s;
        return s;
      }
    }
    /**
     * <code>string accumulation = 2 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int"];</code>
     * @return The bytes for accumulation.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAccumulationBytes() {
      java.lang.Object ref = accumulation_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accumulation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!index_.isEmpty()) {
        output.writeBytes(1, index_);
      }
      if (!getAccumulationBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, accumulation_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!index_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, index_);
      }
      if (!getAccumulationBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, accumulation_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof osmosis.store.v1beta1.Tree.Child)) {
        return super.equals(obj);
      }
      osmosis.store.v1beta1.Tree.Child other = (osmosis.store.v1beta1.Tree.Child) obj;

      if (!getIndex()
          .equals(other.getIndex())) return false;
      if (!getAccumulation()
          .equals(other.getAccumulation())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INDEX_FIELD_NUMBER;
      hash = (53 * hash) + getIndex().hashCode();
      hash = (37 * hash) + ACCUMULATION_FIELD_NUMBER;
      hash = (53 * hash) + getAccumulation().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static osmosis.store.v1beta1.Tree.Child parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static osmosis.store.v1beta1.Tree.Child parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static osmosis.store.v1beta1.Tree.Child parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static osmosis.store.v1beta1.Tree.Child parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static osmosis.store.v1beta1.Tree.Child parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static osmosis.store.v1beta1.Tree.Child parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static osmosis.store.v1beta1.Tree.Child parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static osmosis.store.v1beta1.Tree.Child parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static osmosis.store.v1beta1.Tree.Child parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static osmosis.store.v1beta1.Tree.Child parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static osmosis.store.v1beta1.Tree.Child parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static osmosis.store.v1beta1.Tree.Child parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(osmosis.store.v1beta1.Tree.Child prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code osmosis.store.v1beta1.Child}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:osmosis.store.v1beta1.Child)
        osmosis.store.v1beta1.Tree.ChildOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return osmosis.store.v1beta1.Tree.internal_static_osmosis_store_v1beta1_Child_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return osmosis.store.v1beta1.Tree.internal_static_osmosis_store_v1beta1_Child_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                osmosis.store.v1beta1.Tree.Child.class, osmosis.store.v1beta1.Tree.Child.Builder.class);
      }

      // Construct using osmosis.store.v1beta1.Tree.Child.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        index_ = com.google.protobuf.ByteString.EMPTY;

        accumulation_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return osmosis.store.v1beta1.Tree.internal_static_osmosis_store_v1beta1_Child_descriptor;
      }

      @java.lang.Override
      public osmosis.store.v1beta1.Tree.Child getDefaultInstanceForType() {
        return osmosis.store.v1beta1.Tree.Child.getDefaultInstance();
      }

      @java.lang.Override
      public osmosis.store.v1beta1.Tree.Child build() {
        osmosis.store.v1beta1.Tree.Child result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public osmosis.store.v1beta1.Tree.Child buildPartial() {
        osmosis.store.v1beta1.Tree.Child result = new osmosis.store.v1beta1.Tree.Child(this);
        result.index_ = index_;
        result.accumulation_ = accumulation_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof osmosis.store.v1beta1.Tree.Child) {
          return mergeFrom((osmosis.store.v1beta1.Tree.Child)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(osmosis.store.v1beta1.Tree.Child other) {
        if (other == osmosis.store.v1beta1.Tree.Child.getDefaultInstance()) return this;
        if (other.getIndex() != com.google.protobuf.ByteString.EMPTY) {
          setIndex(other.getIndex());
        }
        if (!other.getAccumulation().isEmpty()) {
          accumulation_ = other.accumulation_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        osmosis.store.v1beta1.Tree.Child parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (osmosis.store.v1beta1.Tree.Child) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString index_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes index = 1;</code>
       * @return The index.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getIndex() {
        return index_;
      }
      /**
       * <code>bytes index = 1;</code>
       * @param value The index to set.
       * @return This builder for chaining.
       */
      public Builder setIndex(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        index_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes index = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIndex() {
        
        index_ = getDefaultInstance().getIndex();
        onChanged();
        return this;
      }

      private java.lang.Object accumulation_ = "";
      /**
       * <code>string accumulation = 2 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int"];</code>
       * @return The accumulation.
       */
      public java.lang.String getAccumulation() {
        java.lang.Object ref = accumulation_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          accumulation_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string accumulation = 2 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int"];</code>
       * @return The bytes for accumulation.
       */
      public com.google.protobuf.ByteString
          getAccumulationBytes() {
        java.lang.Object ref = accumulation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accumulation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string accumulation = 2 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int"];</code>
       * @param value The accumulation to set.
       * @return This builder for chaining.
       */
      public Builder setAccumulation(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        accumulation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string accumulation = 2 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int"];</code>
       * @return This builder for chaining.
       */
      public Builder clearAccumulation() {
        
        accumulation_ = getDefaultInstance().getAccumulation();
        onChanged();
        return this;
      }
      /**
       * <code>string accumulation = 2 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int"];</code>
       * @param value The bytes for accumulation to set.
       * @return This builder for chaining.
       */
      public Builder setAccumulationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        accumulation_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:osmosis.store.v1beta1.Child)
    }

    // @@protoc_insertion_point(class_scope:osmosis.store.v1beta1.Child)
    private static final osmosis.store.v1beta1.Tree.Child DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new osmosis.store.v1beta1.Tree.Child();
    }

    public static osmosis.store.v1beta1.Tree.Child getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Child>
        PARSER = new com.google.protobuf.AbstractParser<Child>() {
      @java.lang.Override
      public Child parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Child(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Child> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Child> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public osmosis.store.v1beta1.Tree.Child getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LeafOrBuilder extends
      // @@protoc_insertion_point(interface_extends:osmosis.store.v1beta1.Leaf)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.osmosis.store.v1beta1.Child leaf = 1;</code>
     * @return Whether the leaf field is set.
     */
    boolean hasLeaf();
    /**
     * <code>.osmosis.store.v1beta1.Child leaf = 1;</code>
     * @return The leaf.
     */
    osmosis.store.v1beta1.Tree.Child getLeaf();
    /**
     * <code>.osmosis.store.v1beta1.Child leaf = 1;</code>
     */
    osmosis.store.v1beta1.Tree.ChildOrBuilder getLeafOrBuilder();
  }
  /**
   * Protobuf type {@code osmosis.store.v1beta1.Leaf}
   */
  public static final class Leaf extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:osmosis.store.v1beta1.Leaf)
      LeafOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Leaf.newBuilder() to construct.
    private Leaf(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Leaf() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Leaf();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Leaf(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              osmosis.store.v1beta1.Tree.Child.Builder subBuilder = null;
              if (leaf_ != null) {
                subBuilder = leaf_.toBuilder();
              }
              leaf_ = input.readMessage(osmosis.store.v1beta1.Tree.Child.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(leaf_);
                leaf_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return osmosis.store.v1beta1.Tree.internal_static_osmosis_store_v1beta1_Leaf_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return osmosis.store.v1beta1.Tree.internal_static_osmosis_store_v1beta1_Leaf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              osmosis.store.v1beta1.Tree.Leaf.class, osmosis.store.v1beta1.Tree.Leaf.Builder.class);
    }

    public static final int LEAF_FIELD_NUMBER = 1;
    private osmosis.store.v1beta1.Tree.Child leaf_;
    /**
     * <code>.osmosis.store.v1beta1.Child leaf = 1;</code>
     * @return Whether the leaf field is set.
     */
    @java.lang.Override
    public boolean hasLeaf() {
      return leaf_ != null;
    }
    /**
     * <code>.osmosis.store.v1beta1.Child leaf = 1;</code>
     * @return The leaf.
     */
    @java.lang.Override
    public osmosis.store.v1beta1.Tree.Child getLeaf() {
      return leaf_ == null ? osmosis.store.v1beta1.Tree.Child.getDefaultInstance() : leaf_;
    }
    /**
     * <code>.osmosis.store.v1beta1.Child leaf = 1;</code>
     */
    @java.lang.Override
    public osmosis.store.v1beta1.Tree.ChildOrBuilder getLeafOrBuilder() {
      return getLeaf();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (leaf_ != null) {
        output.writeMessage(1, getLeaf());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (leaf_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getLeaf());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof osmosis.store.v1beta1.Tree.Leaf)) {
        return super.equals(obj);
      }
      osmosis.store.v1beta1.Tree.Leaf other = (osmosis.store.v1beta1.Tree.Leaf) obj;

      if (hasLeaf() != other.hasLeaf()) return false;
      if (hasLeaf()) {
        if (!getLeaf()
            .equals(other.getLeaf())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasLeaf()) {
        hash = (37 * hash) + LEAF_FIELD_NUMBER;
        hash = (53 * hash) + getLeaf().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static osmosis.store.v1beta1.Tree.Leaf parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static osmosis.store.v1beta1.Tree.Leaf parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static osmosis.store.v1beta1.Tree.Leaf parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static osmosis.store.v1beta1.Tree.Leaf parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static osmosis.store.v1beta1.Tree.Leaf parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static osmosis.store.v1beta1.Tree.Leaf parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static osmosis.store.v1beta1.Tree.Leaf parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static osmosis.store.v1beta1.Tree.Leaf parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static osmosis.store.v1beta1.Tree.Leaf parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static osmosis.store.v1beta1.Tree.Leaf parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static osmosis.store.v1beta1.Tree.Leaf parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static osmosis.store.v1beta1.Tree.Leaf parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(osmosis.store.v1beta1.Tree.Leaf prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code osmosis.store.v1beta1.Leaf}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:osmosis.store.v1beta1.Leaf)
        osmosis.store.v1beta1.Tree.LeafOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return osmosis.store.v1beta1.Tree.internal_static_osmosis_store_v1beta1_Leaf_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return osmosis.store.v1beta1.Tree.internal_static_osmosis_store_v1beta1_Leaf_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                osmosis.store.v1beta1.Tree.Leaf.class, osmosis.store.v1beta1.Tree.Leaf.Builder.class);
      }

      // Construct using osmosis.store.v1beta1.Tree.Leaf.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (leafBuilder_ == null) {
          leaf_ = null;
        } else {
          leaf_ = null;
          leafBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return osmosis.store.v1beta1.Tree.internal_static_osmosis_store_v1beta1_Leaf_descriptor;
      }

      @java.lang.Override
      public osmosis.store.v1beta1.Tree.Leaf getDefaultInstanceForType() {
        return osmosis.store.v1beta1.Tree.Leaf.getDefaultInstance();
      }

      @java.lang.Override
      public osmosis.store.v1beta1.Tree.Leaf build() {
        osmosis.store.v1beta1.Tree.Leaf result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public osmosis.store.v1beta1.Tree.Leaf buildPartial() {
        osmosis.store.v1beta1.Tree.Leaf result = new osmosis.store.v1beta1.Tree.Leaf(this);
        if (leafBuilder_ == null) {
          result.leaf_ = leaf_;
        } else {
          result.leaf_ = leafBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof osmosis.store.v1beta1.Tree.Leaf) {
          return mergeFrom((osmosis.store.v1beta1.Tree.Leaf)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(osmosis.store.v1beta1.Tree.Leaf other) {
        if (other == osmosis.store.v1beta1.Tree.Leaf.getDefaultInstance()) return this;
        if (other.hasLeaf()) {
          mergeLeaf(other.getLeaf());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        osmosis.store.v1beta1.Tree.Leaf parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (osmosis.store.v1beta1.Tree.Leaf) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private osmosis.store.v1beta1.Tree.Child leaf_;
      private com.google.protobuf.SingleFieldBuilderV3<
          osmosis.store.v1beta1.Tree.Child, osmosis.store.v1beta1.Tree.Child.Builder, osmosis.store.v1beta1.Tree.ChildOrBuilder> leafBuilder_;
      /**
       * <code>.osmosis.store.v1beta1.Child leaf = 1;</code>
       * @return Whether the leaf field is set.
       */
      public boolean hasLeaf() {
        return leafBuilder_ != null || leaf_ != null;
      }
      /**
       * <code>.osmosis.store.v1beta1.Child leaf = 1;</code>
       * @return The leaf.
       */
      public osmosis.store.v1beta1.Tree.Child getLeaf() {
        if (leafBuilder_ == null) {
          return leaf_ == null ? osmosis.store.v1beta1.Tree.Child.getDefaultInstance() : leaf_;
        } else {
          return leafBuilder_.getMessage();
        }
      }
      /**
       * <code>.osmosis.store.v1beta1.Child leaf = 1;</code>
       */
      public Builder setLeaf(osmosis.store.v1beta1.Tree.Child value) {
        if (leafBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          leaf_ = value;
          onChanged();
        } else {
          leafBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.osmosis.store.v1beta1.Child leaf = 1;</code>
       */
      public Builder setLeaf(
          osmosis.store.v1beta1.Tree.Child.Builder builderForValue) {
        if (leafBuilder_ == null) {
          leaf_ = builderForValue.build();
          onChanged();
        } else {
          leafBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.osmosis.store.v1beta1.Child leaf = 1;</code>
       */
      public Builder mergeLeaf(osmosis.store.v1beta1.Tree.Child value) {
        if (leafBuilder_ == null) {
          if (leaf_ != null) {
            leaf_ =
              osmosis.store.v1beta1.Tree.Child.newBuilder(leaf_).mergeFrom(value).buildPartial();
          } else {
            leaf_ = value;
          }
          onChanged();
        } else {
          leafBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.osmosis.store.v1beta1.Child leaf = 1;</code>
       */
      public Builder clearLeaf() {
        if (leafBuilder_ == null) {
          leaf_ = null;
          onChanged();
        } else {
          leaf_ = null;
          leafBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.osmosis.store.v1beta1.Child leaf = 1;</code>
       */
      public osmosis.store.v1beta1.Tree.Child.Builder getLeafBuilder() {
        
        onChanged();
        return getLeafFieldBuilder().getBuilder();
      }
      /**
       * <code>.osmosis.store.v1beta1.Child leaf = 1;</code>
       */
      public osmosis.store.v1beta1.Tree.ChildOrBuilder getLeafOrBuilder() {
        if (leafBuilder_ != null) {
          return leafBuilder_.getMessageOrBuilder();
        } else {
          return leaf_ == null ?
              osmosis.store.v1beta1.Tree.Child.getDefaultInstance() : leaf_;
        }
      }
      /**
       * <code>.osmosis.store.v1beta1.Child leaf = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          osmosis.store.v1beta1.Tree.Child, osmosis.store.v1beta1.Tree.Child.Builder, osmosis.store.v1beta1.Tree.ChildOrBuilder> 
          getLeafFieldBuilder() {
        if (leafBuilder_ == null) {
          leafBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              osmosis.store.v1beta1.Tree.Child, osmosis.store.v1beta1.Tree.Child.Builder, osmosis.store.v1beta1.Tree.ChildOrBuilder>(
                  getLeaf(),
                  getParentForChildren(),
                  isClean());
          leaf_ = null;
        }
        return leafBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:osmosis.store.v1beta1.Leaf)
    }

    // @@protoc_insertion_point(class_scope:osmosis.store.v1beta1.Leaf)
    private static final osmosis.store.v1beta1.Tree.Leaf DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new osmosis.store.v1beta1.Tree.Leaf();
    }

    public static osmosis.store.v1beta1.Tree.Leaf getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Leaf>
        PARSER = new com.google.protobuf.AbstractParser<Leaf>() {
      @java.lang.Override
      public Leaf parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Leaf(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Leaf> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Leaf> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public osmosis.store.v1beta1.Tree.Leaf getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_osmosis_store_v1beta1_Node_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_osmosis_store_v1beta1_Node_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_osmosis_store_v1beta1_Child_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_osmosis_store_v1beta1_Child_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_osmosis_store_v1beta1_Leaf_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_osmosis_store_v1beta1_Leaf_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n osmosis/store/v1beta1/tree.proto\022\025osmo" +
      "sis.store.v1beta1\032\024gogoproto/gogo.proto\032" +
      "\036cosmos/base/v1beta1/coin.proto\"6\n\004Node\022" +
      ".\n\010children\030\001 \003(\0132\034.osmosis.store.v1beta" +
      "1.Child\"\\\n\005Child\022\r\n\005index\030\001 \001(\014\022D\n\014accum" +
      "ulation\030\002 \001(\tB.\332\336\037&github.com/cosmos/cos" +
      "mos-sdk/types.Int\310\336\037\000\"2\n\004Leaf\022*\n\004leaf\030\001 " +
      "\001(\0132\034.osmosis.store.v1beta1.ChildB\'Z%git" +
      "hub.com/osmosis-labs/osmosis/storeb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.GoGoProtos.getDescriptor(),
          cosmos.base.v1beta1.CoinOuterClass.getDescriptor(),
        });
    internal_static_osmosis_store_v1beta1_Node_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_osmosis_store_v1beta1_Node_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_osmosis_store_v1beta1_Node_descriptor,
        new java.lang.String[] { "Children", });
    internal_static_osmosis_store_v1beta1_Child_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_osmosis_store_v1beta1_Child_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_osmosis_store_v1beta1_Child_descriptor,
        new java.lang.String[] { "Index", "Accumulation", });
    internal_static_osmosis_store_v1beta1_Leaf_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_osmosis_store_v1beta1_Leaf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_osmosis_store_v1beta1_Leaf_descriptor,
        new java.lang.String[] { "Leaf", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf.GoGoProtos.customtype);
    registry.add(com.google.protobuf.GoGoProtos.nullable);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.GoGoProtos.getDescriptor();
    cosmos.base.v1beta1.CoinOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
